"""Knowledge atoms — self-contained theorems, definitions, and formulas.

Each domain module registers its atoms via register_atom().
Importing this package triggers all registrations.
"""
# Original domain atoms
from engram_generator.atoms import physics  # noqa: F401
from engram_generator.atoms import science  # noqa: F401
from engram_generator.atoms import reasoning  # noqa: F401
from engram_generator.atoms import mathematics  # noqa: F401
from engram_generator.atoms import calculus  # noqa: F401
from engram_generator.atoms import sourced  # noqa: F401
from engram_generator.atoms import ai_ml  # noqa: F401
from engram_generator.atoms import oos  # noqa: F401

# New domain atoms (properly separated)
from engram_generator.atoms import geometry  # noqa: F401
from engram_generator.atoms import logic  # noqa: F401
from engram_generator.atoms import set_theory  # noqa: F401
from engram_generator.atoms import strings  # noqa: F401
from engram_generator.atoms import trigonometry  # noqa: F401
from engram_generator.atoms import measurement  # noqa: F401
from engram_generator.atoms import sequences  # noqa: F401
from engram_generator.atoms import combinatorics  # noqa: F401
from engram_generator.atoms import chemistry  # noqa: F401
from engram_generator.atoms import economics  # noqa: F401
from engram_generator.atoms import game_theory  # noqa: F401
from engram_generator.atoms import automata  # noqa: F401
from engram_generator.atoms import spatial  # noqa: F401
from engram_generator.atoms import numerical  # noqa: F401
from engram_generator.atoms import graph_ds_recursion  # noqa: F401
from engram_generator.atoms import bridge_deep  # noqa: F401
from engram_generator.atoms import electromagnetism  # noqa: F401
from engram_generator.atoms import missing_fill  # noqa: F401
from engram_generator.atoms import thermodynamics_atoms  # noqa: F401
from engram_generator.atoms import calculus_ext_atoms  # noqa: F401
from engram_generator.atoms import analysis_probability_atoms  # noqa: F401
from engram_generator.atoms import mechanics_chemistry_atoms  # noqa: F401
from engram_generator.atoms import algebra_atoms  # noqa: F401
from engram_generator.atoms import crypto_functional_atoms  # noqa: F401
from engram_generator.atoms import open_problems_atoms  # noqa: F401
from engram_generator.atoms import ml_geometry_atoms  # noqa: F401
from engram_generator.atoms import statmech_discrete_atoms  # noqa: F401
from engram_generator.atoms import number_theory_atoms  # noqa: F401
from engram_generator.atoms import ml_theory_neuro_atoms  # noqa: F401
from engram_generator.atoms import ml_geometry_open_atoms  # noqa: F401
from engram_generator.atoms import bio_eco_atoms  # noqa: F401
from engram_generator.atoms import em_combinatorics_atoms  # noqa: F401
from engram_generator.atoms import quantum_stats_atoms  # noqa: F401
from engram_generator.atoms import algorithms_chemistry_atoms  # noqa: F401
from engram_generator.atoms import physics_ext_atoms  # noqa: F401
from engram_generator.atoms import topology_measure_complex_atoms  # noqa: F401
from engram_generator.atoms import relativity_pde_stochastic_atoms  # noqa: F401
from engram_generator.atoms import physchem_genetics_epi_atoms  # noqa: F401
from engram_generator.atoms import distributed_formal_category_atoms  # noqa: F401
from engram_generator.atoms import diffgeo_algnum_algtop_atoms  # noqa: F401
from engram_generator.atoms import inorganic_spectro_cell_atoms  # noqa: F401
from engram_generator.atoms import info_signal_control_atoms  # noqa: F401
from engram_generator.atoms import homological_harmonic_logic_atoms  # noqa: F401
from engram_generator.atoms import stats_algebra_analysis_ext_atoms  # noqa: F401
from engram_generator.atoms import physchem_algebra_bio_deep_atoms  # noqa: F401
from engram_generator.atoms import engineering_quantum_prob_atoms  # noqa: F401
from engram_generator.atoms import econ_qinfo_systems_atoms  # noqa: F401
from engram_generator.atoms import ml_numtheory_combi_ext_atoms  # noqa: F401
from engram_generator.atoms import nonlinear_solidstate_mechanics_atoms  # noqa: F401
from engram_generator.atoms import meta_advprob_advml_atoms  # noqa: F401
from engram_generator.atoms import algpat_alggeom_particle_atoms  # noqa: F401
from engram_generator.atoms import gr_decision_numerical_atoms  # noqa: F401
from engram_generator.atoms import combopt_graphics_advgraph_atoms  # noqa: F401
from engram_generator.atoms import mathphys_finmath_formal_atoms  # noqa: F401
from engram_generator.atoms import mathphys_finmath_formal_atoms  # noqa: F401
from engram_generator.atoms import meta9_opsres_orgchem_atoms  # noqa: F401
from engram_generator.atoms import eco_gen_biochem_ext_atoms  # noqa: F401
from engram_generator.atoms import mathphys_finmath_formal_atoms  # noqa: F401
from engram_generator.atoms import sysbio_topext_metaext_atoms  # noqa: F401
from engram_generator.atoms import batch_ext_atoms  # noqa: F401
from engram_generator.atoms import astro_materials_relativity_ext_atoms  # noqa: F401
from engram_generator.atoms import pde_inorganic_genchem_ext_atoms  # noqa: F401
from engram_generator.atoms import topdeep_logic_cstheory_atoms  # noqa: F401
from engram_generator.atoms import ds_graphs_econ_ext_atoms  # noqa: F401
from engram_generator.atoms import signal_solidstate_qinfo_ext_atoms  # noqa: F401
from engram_generator.atoms import thermo_optics_robot_ext_atoms  # noqa: F401
from engram_generator.atoms import control_gamedeep_opticsdeep_atoms  # noqa: F401
from engram_generator.atoms import thermodeep_fluiddeep_logicdeep_atoms  # noqa: F401
from engram_generator.atoms import os_distributed_compilers_deep_atoms  # noqa: F401
from engram_generator.atoms import networks_econ_spectro_deep_atoms  # noqa: F401
from engram_generator.atoms import ext_batch_atoms  # noqa: F401
from engram_generator.atoms import bioinfo_pharma_qm_reptheory_atoms  # noqa: F401
from engram_generator.atoms import opt_astro_compilers_stochcalc_atoms  # noqa: F401
from engram_generator.atoms import crypto_topo2_pde_funcext_atoms  # noqa: F401
from engram_generator.atoms import climate_biostats_tensor_network_cognitive_atoms  # noqa: F401
from engram_generator.atoms import qft_telecom_robotics_ocean_geophys_atoms  # noqa: F401
from engram_generator.atoms import computability_proof_materials_aero_power_atoms  # noqa: F401
from engram_generator.atoms import crypto_ext_atoms  # noqa: F401
from engram_generator.atoms import continuum_mechanics_atoms  # noqa: F401
from engram_generator.atoms import music_plasma_qec_atoms  # noqa: F401
from engram_generator.atoms import persistent_game_spatial_atoms  # noqa: F401
from engram_generator.atoms import automata_diffeq_trig_atoms  # noqa: F401
from engram_generator.atoms import actuarial_medical_meta_atoms  # noqa: F401
from engram_generator.atoms import diffgeo_measure_photon_semi_atoms  # noqa: F401
from engram_generator.atoms import antenna_polymer_atoms  # noqa: F401
from engram_generator.atoms import queuing_bayesian_causal_atoms  # noqa: F401
from engram_generator.atoms import coding_wavelet_arch_atoms  # noqa: F401
from engram_generator.atoms import timeseries_numlinalg_digelec_atoms  # noqa: F401
from engram_generator.atoms import struct_heat_emext_cellbio_atoms  # noqa: F401
from engram_generator.atoms import seq_geo_meas_ling_info_net_nuc_fluid_atoms  # noqa: F401
from engram_generator.atoms import recursion_automata_numext_atoms  # noqa: F401
