"""Knowledge atoms for specialized domains (batch 3).

Covers: persistent_homology, diffgeo_ext, diffeq_ext, trigonometry_ext,
sequences_ext, measure_ext, model_theory, category_ext,
convex_optimization, numerical_linalg, numerical_ext2,
actuarial, medical_imaging, cell_biology_ext, geology_ext,
linguistics, linguistics_ext, measurement_ext,
meta_reasoning_ext2, info_theory_ext, info_theory_deep,
nuclear_ext.
"""
from engram_generator.base import Atom
from engram_generator.atoms.registry import register_atom


# ---------------------------------------------------------------------------
# Persistent homology (tier 5-6)
# ---------------------------------------------------------------------------

register_atom(Atom(atom_type="concept", name="simplicial_complex", content="A simplicial complex is a collection of simplices (vertices, edges, triangles, tetrahedra, ...) closed under taking faces. The Rips complex connects points within distance epsilon. Geometric realisation gives a topological space from discrete data.", example="Points {A,B,C} with d(A,B)=1, d(B,C)=1, d(A,C)=2. At epsilon=1.5: edges AB,BC but not AC. Triangle ABC not included.", tier=5, domain="topology", source="Wikipedia contributors, 'Simplicial complex', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Simplicial_complex", prerequisites=[]))

register_atom(Atom(atom_type="algorithm", name="boundary_operator", content="The boundary operator d_n maps n-simplices to (n-1)-chains: d_n([v0,...,vn]) = sum(-1)^i [v0,...,v_hat_i,...,vn]. Key property: d_{n-1} . d_n = 0. This defines a chain complex and homology groups H_n = ker(d_n)/im(d_{n+1}).", example="d_1([A,B]) = [B]-[A]. d_2([A,B,C]) = [B,C]-[A,C]+[A,B]. d_1(d_2([A,B,C])) = (C-B)-(C-A)+(B-A) = 0.", tier=6, domain="topology", source="Wikipedia contributors, 'Simplicial homology', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Simplicial_homology", prerequisites=["simplicial_complex"]))

register_atom(Atom(atom_type="formula", name="betti_from_complex", content="Betti numbers b_k = rank(H_k) count the number of k-dimensional 'holes': b_0 = connected components, b_1 = loops/tunnels, b_2 = voids. Computed as b_k = rank(ker(d_k)) - rank(im(d_{k+1})). Euler characteristic chi = sum(-1)^k * b_k.", example="Torus: b_0=1, b_1=2, b_2=1. chi = 1-2+1 = 0.", tier=6, domain="topology", source="Wikipedia contributors, 'Betti number', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Betti_number", prerequisites=["boundary_operator"]))

register_atom(Atom(atom_type="concept", name="vietoris_rips", content="The Vietoris-Rips complex at scale epsilon includes a simplex [v0,...,vk] iff all pairwise distances d(vi,vj) <= epsilon. Easier to compute than Cech complex. As epsilon varies, simplices appear/disappear, generating a persistence module.", example="3 points: A,B at distance 1, B,C at 1.5, A,C at 2. At epsilon=1: edge AB only. At 1.5: edges AB,BC. At 2: triangle ABC.", tier=6, domain="topology", source="Wikipedia contributors, 'Vietoris-Rips complex', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Vietoris%E2%80%93Rips_complex", prerequisites=["simplicial_complex"]))

register_atom(Atom(atom_type="concept", name="persistence_diagram", content="A persistence diagram plots (birth, death) of topological features across scales. Long-lived features (far from diagonal) represent significant topology; short-lived features are noise. Computed via the persistence algorithm on filtered simplicial complexes.", example="Point cloud forming a circle: H_0 pair born at 0, dies when circle connects. H_1 pair born when loop appears, dies when filled. Loop has large persistence.", tier=6, domain="topology", source="Wikipedia contributors, 'Persistent homology', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Persistent_homology", prerequisites=["vietoris_rips"]))

register_atom(Atom(atom_type="formula", name="bottleneck_distance", content="The bottleneck distance between persistence diagrams P and Q is: d_B(P,Q) = inf_{gamma} sup_x ||x - gamma(x)||_inf, where gamma ranges over bijections (including diagonal points). Measures the maximum discrepancy between matched features. Stability theorem: small perturbations in data give small bottleneck distances.", example="P = {(0,3), (1,2)}. Q = {(0,2.8), (0.9,2.1)}. Optimal matching gives d_B = max(0.2, 0.14) = 0.2.", tier=6, domain="topology", source="Wikipedia contributors, 'Persistent homology', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Persistent_homology#Stability", prerequisites=["persistence_diagram"]))

# ---------------------------------------------------------------------------
# Differential geometry ext (tier 6-7)
# ---------------------------------------------------------------------------

register_atom(Atom(atom_type="formula", name="frenet_serret", content="The Frenet-Serret formulas describe a curve in 3D: T' = kappa*N, N' = -kappa*T + tau*B, B' = -tau*N, where T is tangent, N is normal, B is binormal, kappa is curvature, tau is torsion. They form an orthonormal frame moving along the curve.", example="Helix r(t) = (cos t, sin t, t). T=(-sin t, cos t, 1)/sqrt(2). kappa = 1/2, tau = 1/2. Constant curvature and torsion.", tier=6, domain="differential_geometry", source="Wikipedia contributors, 'Frenet-Serret formulas', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Frenet%E2%80%93Serret_formulas", prerequisites=["cross_product"]))

register_atom(Atom(atom_type="formula", name="surface_normal", content="The surface normal at a point on a parametric surface r(u,v) is n = (r_u x r_v) / |r_u x r_v|, where r_u and r_v are partial derivatives. For an implicit surface F(x,y,z) = 0: n = grad(F) / |grad(F)|.", example="Sphere: F = x^2+y^2+z^2-1. grad F = (2x,2y,2z). At (1,0,0): n = (2,0,0)/2 = (1,0,0).", tier=6, domain="differential_geometry", source="Wikipedia contributors, 'Normal (geometry)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Normal_(geometry)", prerequisites=["cross_product"]))

register_atom(Atom(atom_type="formula", name="first_fundamental_form", content="The first fundamental form of a surface measures lengths and angles: I = E*du^2 + 2F*du*dv + G*dv^2, where E = r_u.r_u, F = r_u.r_v, G = r_v.r_v. Area element dA = sqrt(EG-F^2) du dv.", example="Sphere r(u,v) = (sin u cos v, sin u sin v, cos u). E=1, F=0, G=sin^2 u. dA = sin u du dv.", tier=6, domain="differential_geometry", source="Wikipedia contributors, 'First fundamental form', Wikipedia.", source_url="https://en.wikipedia.org/wiki/First_fundamental_form", prerequisites=["dot_product"]))

register_atom(Atom(atom_type="formula", name="second_fundamental_form", content="The second fundamental form II = e*du^2 + 2f*du*dv + g*dv^2 measures curvature, where e = r_uu.n, f = r_uv.n, g = r_vv.n. Gaussian curvature K = (eg-f^2)/(EG-F^2). Mean curvature H = (eG-2fF+gE)/(2(EG-F^2)).", example="Sphere of radius R: e=g=1/R, f=0, E=G=R^2, F=0. K = 1/R^2. H = 1/R.", tier=7, domain="differential_geometry", source="Wikipedia contributors, 'Second fundamental form', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Second_fundamental_form", prerequisites=["first_fundamental_form"]))

register_atom(Atom(atom_type="formula", name="mean_curvature", content="Mean curvature H = (kappa_1 + kappa_2)/2, where kappa_1 and kappa_2 are principal curvatures. Minimal surfaces have H = 0 everywhere (soap films). H = (eG - 2fF + gE) / (2(EG-F^2)) from fundamental forms.", example="Cylinder radius R: kappa_1 = 1/R, kappa_2 = 0. H = 1/(2R). Not a minimal surface.", tier=7, domain="differential_geometry", source="Wikipedia contributors, 'Mean curvature', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Mean_curvature", prerequisites=["second_fundamental_form"]))

register_atom(Atom(atom_type="concept", name="parallel_transport", content="Parallel transport moves a vector along a curve while keeping it 'as parallel as possible' (covariant derivative = 0). On a curved surface, parallel transport around a closed loop rotates the vector by the holonomy angle, proportional to the enclosed Gaussian curvature.", example="On a sphere: transport a vector from North Pole along 0-deg meridian to equator, along equator to 90-deg meridian, back to pole. Vector rotates 90 degrees.", tier=7, domain="differential_geometry", source="Wikipedia contributors, 'Parallel transport', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Parallel_transport", prerequisites=["christoffel_symbol"]))

# ---------------------------------------------------------------------------
# Differential equations ext (tier 5-6)
# ---------------------------------------------------------------------------

register_atom(Atom(atom_type="method", name="variation_of_parameters", content="Variation of parameters solves non-homogeneous linear ODEs y'' + p(x)y' + q(x)y = g(x). Given homogeneous solutions y1, y2, the particular solution is y_p = -y1*integral(y2*g/W) + y2*integral(y1*g/W), where W = y1*y2' - y2*y1' is the Wronskian.", example="y'' + y = sec(x). y1=cos x, y2=sin x, W=1. y_p = -cos x * integral(sin x * sec x) + sin x * integral(cos x * sec x) = -cos x * integral(tan x) + sin x * x.", tier=6, domain="differential_equations", source="Wikipedia contributors, 'Variation of parameters', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Variation_of_parameters", prerequisites=["second_derivative"]))

register_atom(Atom(atom_type="method", name="laplace_solve_ode", content="Solving ODEs via Laplace transform: (1) take L{} of both sides, (2) use L{y'} = sY - y(0), L{y''} = s^2Y - sy(0) - y'(0), (3) solve for Y(s), (4) inverse Laplace to get y(t). Handles initial conditions automatically.", example="y' + 2y = 3, y(0) = 1. L: sY - 1 + 2Y = 3/s. Y = (3/s + 1)/(s+2) = 3/(s(s+2)) + 1/(s+2). y(t) = 3/2*(1-e^{-2t}) + e^{-2t} = 3/2 - 1/2*e^{-2t}.", tier=5, domain="differential_equations", source="Wikipedia contributors, 'Laplace transform applied to differential equations', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Laplace_transform_applied_to_differential_equations", prerequisites=["laplace_transform"]))

register_atom(Atom(atom_type="method", name="system_ode_matrix", content="A system of linear ODEs x' = Ax has solution x(t) = exp(At)*x(0). For diagonalisable A = PDP^{-1}: exp(At) = P*diag(exp(lambda_i*t))*P^{-1}. Eigenvalues determine stability: all Re(lambda) < 0 -> asymptotically stable.", example="x'=[[0,1],[-2,-3]]x. Eigenvalues: -1,-2 (both negative -> stable). x(t) = c1*v1*e^{-t} + c2*v2*e^{-2t}.", tier=6, domain="differential_equations", source="Wikipedia contributors, 'Matrix exponential', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Matrix_exponential", prerequisites=["eigenvalue"]))

register_atom(Atom(atom_type="method", name="boundary_value", content="Boundary value problems specify conditions at two points: y(a)=A, y(b)=B. Shooting method: guess y'(a), solve IVP, adjust guess until y(b)=B. Finite difference: discretise domain, solve system of linear equations. Green's function method for linear problems.", example="y'' = -pi^2*y, y(0)=0, y(1)=0. Solution: y = C*sin(pi*x). Boundary conditions determine C.", tier=6, domain="differential_equations", source="Wikipedia contributors, 'Boundary value problem', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Boundary_value_problem", prerequisites=["system_equations"]))

register_atom(Atom(atom_type="concept", name="stability_ode", content="Equilibrium x* of x' = f(x) is stable if nearby solutions stay nearby. Asymptotically stable: solutions converge to x*. Linearisation: x' = Df(x*) * (x - x*). Stable if all eigenvalues of Df have negative real parts. Lyapunov's direct method: find V(x) > 0 with V'(x) < 0.", example="x' = -x^3. Equilibrium x*=0. V=x^2, V' = 2x*(-x^3) = -2x^4 < 0. Asymptotically stable.", tier=6, domain="differential_equations", source="Wikipedia contributors, 'Stability theory', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Stability_theory", prerequisites=["eigenvalue"]))

register_atom(Atom(atom_type="method", name="exact_ode", content="An ODE M(x,y)dx + N(x,y)dy = 0 is exact if dM/dy = dN/dx. Solution: F(x,y) = C where dF/dx = M, dF/dy = N. If not exact, an integrating factor mu may make it exact: mu*M dx + mu*N dy = 0.", example="(2xy+3)dx + (x^2-1)dy = 0. dM/dy = 2x = dN/dx. Exact. F = x^2*y + 3x - y = C.", tier=5, domain="differential_equations", source="Wikipedia contributors, 'Exact differential equation', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Exact_differential_equation", prerequisites=["partial_derivative"]))

# ---------------------------------------------------------------------------
# Trigonometry ext (tier 4-5)
# ---------------------------------------------------------------------------

register_atom(Atom(atom_type="formula", name="inverse_trig", content="Inverse trig functions: arcsin(x) returns angle in [-pi/2, pi/2], arccos(x) in [0, pi], arctan(x) in (-pi/2, pi/2). Derivatives: d/dx arcsin(x) = 1/sqrt(1-x^2), d/dx arctan(x) = 1/(1+x^2).", example="arcsin(0.5) = pi/6 = 30 deg. arccos(0.5) = pi/3 = 60 deg. arctan(1) = pi/4 = 45 deg.", tier=4, domain="trigonometry", source="Wikipedia contributors, 'Inverse trigonometric functions', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Inverse_trigonometric_functions", prerequisites=["sin_cos_eval"]))

register_atom(Atom(atom_type="formula", name="hyperbolic_functions", content="Hyperbolic functions: sinh(x) = (e^x - e^(-x))/2, cosh(x) = (e^x + e^(-x))/2, tanh(x) = sinh(x)/cosh(x). Identity: cosh^2(x) - sinh^2(x) = 1. Derivatives: d/dx sinh(x) = cosh(x), d/dx cosh(x) = sinh(x).", example="sinh(1) = (e-1/e)/2 = (2.718-0.368)/2 = 1.175. cosh(1) = (e+1/e)/2 = 1.543. tanh(1) = 0.762.", tier=5, domain="trigonometry", source="Wikipedia contributors, 'Hyperbolic functions', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Hyperbolic_functions", prerequisites=["exponentiation"]))

register_atom(Atom(atom_type="method", name="trig_equation", content="Solving trigonometric equations: use identities to simplify, then solve for the angle. sin(x)=a: x = arcsin(a) + 2n*pi or pi-arcsin(a) + 2n*pi. cos(x)=a: x = +/-arccos(a) + 2n*pi. tan(x)=a: x = arctan(a) + n*pi.", example="2*sin(x)-1=0 -> sin(x)=0.5 -> x=pi/6 + 2n*pi or 5*pi/6 + 2n*pi.", tier=5, domain="trigonometry", source="Wikipedia contributors, 'Trigonometric equation', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Trigonometric_equation", prerequisites=["inverse_trig"]))

register_atom(Atom(atom_type="formula", name="double_angle", content="Double angle formulas: sin(2x) = 2*sin(x)*cos(x). cos(2x) = cos^2(x) - sin^2(x) = 2*cos^2(x)-1 = 1-2*sin^2(x). tan(2x) = 2*tan(x)/(1-tan^2(x)). Half-angle: sin(x/2) = sqrt((1-cos(x))/2).", example="x = 30 deg. sin(60) = 2*sin(30)*cos(30) = 2*0.5*0.866 = 0.866. cos(60) = 2*cos^2(30)-1 = 2*0.75-1 = 0.5.", tier=4, domain="trigonometry", source="Wikipedia contributors, 'List of trigonometric identities', Wikipedia.", source_url="https://en.wikipedia.org/wiki/List_of_trigonometric_identities#Double-angle_formulae", prerequisites=["sin_cos_eval"]))

register_atom(Atom(atom_type="formula", name="inverse_hyperbolic", content="Inverse hyperbolic functions: arsinh(x) = ln(x + sqrt(x^2+1)), arcosh(x) = ln(x + sqrt(x^2-1)) for x>=1, artanh(x) = 0.5*ln((1+x)/(1-x)) for |x|<1. Used in integration of sqrt(x^2+/-1) forms.", example="arsinh(1) = ln(1+sqrt(2)) = ln(2.414) = 0.881. arcosh(2) = ln(2+sqrt(3)) = ln(3.732) = 1.317.", tier=5, domain="trigonometry", source="Wikipedia contributors, 'Inverse hyperbolic functions', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Inverse_hyperbolic_functions", prerequisites=["hyperbolic_functions"]))

register_atom(Atom(atom_type="method", name="trig_substitution", content="Trigonometric substitution simplifies integrals containing sqrt(a^2-x^2), sqrt(a^2+x^2), or sqrt(x^2-a^2). Substitutions: x=a*sin(t), x=a*tan(t), x=a*sec(t) respectively. Converts to trigonometric integrals.", example="integral sqrt(1-x^2) dx. Let x=sin(t), dx=cos(t)dt. integral cos^2(t)dt = t/2 + sin(2t)/4 + C = arcsin(x)/2 + x*sqrt(1-x^2)/2 + C.", tier=5, domain="trigonometry", source="Wikipedia contributors, 'Trigonometric substitution', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Trigonometric_substitution", prerequisites=["inverse_trig"]))

# ---------------------------------------------------------------------------
# Sequences ext (tier 4-5)
# ---------------------------------------------------------------------------

register_atom(Atom(atom_type="formula", name="harmonic_series", content="The harmonic series sum(1/n) from n=1 to infinity diverges. Partial sums H_n = 1 + 1/2 + 1/3 + ... + 1/n ~ ln(n) + gamma, where gamma = 0.5772... is the Euler-Mascheroni constant. The alternating harmonic series sum((-1)^(n+1)/n) = ln(2).", example="H_10 = 1+0.5+0.333+0.25+0.2+0.167+0.143+0.125+0.111+0.1 = 2.929. ln(10)+0.577 = 2.880.", tier=4, domain="sequences", source="Wikipedia contributors, 'Harmonic series (mathematics)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Harmonic_series_(mathematics)", prerequisites=["summation"]))

register_atom(Atom(atom_type="formula", name="telescoping_series", content="A telescoping series has partial sums that simplify by cancellation: sum(a_n - a_{n+1}) = a_1 - lim a_n. Example: sum(1/(n(n+1))) = sum(1/n - 1/(n+1)) = 1 - lim 1/(n+1) = 1.", example="sum_{n=1}^{N} 1/(n(n+1)) = 1 - 1/(N+1). As N->inf: sum = 1.", tier=4, domain="sequences", source="Wikipedia contributors, 'Telescoping series', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Telescoping_series", prerequisites=["partial_fractions"]))

register_atom(Atom(atom_type="formula", name="recurrence_second_order", content="A second-order linear recurrence a_n = p*a_{n-1} + q*a_{n-2} has solution a_n = A*r1^n + B*r2^n, where r1,r2 are roots of x^2 - px - q = 0. If r1=r2: a_n = (A+Bn)*r^n. Fibonacci: a_n = a_{n-1}+a_{n-2}, roots (1+/-sqrt(5))/2.", example="a_n = 3*a_{n-1} - 2*a_{n-2}, a_0=1, a_1=3. Char eq: x^2-3x+2=0, roots 1,2. a_n = -1*1^n + 2*2^n = 2^{n+1}-1.", tier=5, domain="sequences", source="Wikipedia contributors, 'Recurrence relation', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Recurrence_relation#Solving_linear_recurrence_relations", prerequisites=["quadratic"]))

register_atom(Atom(atom_type="formula", name="power_series_eval", content="A power series sum(a_n * x^n) converges within radius R = 1/limsup|a_n|^(1/n) (root test) or R = lim|a_n/a_{n+1}| (ratio test). Common: e^x = sum x^n/n!, sin x = sum (-1)^n x^{2n+1}/(2n+1)!, 1/(1-x) = sum x^n for |x|<1.", example="e^1 = sum 1/n! = 1+1+0.5+0.167+0.042+... = 2.718. Converges for all x (R=inf).", tier=5, domain="sequences", source="Wikipedia contributors, 'Power series', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Power_series", prerequisites=["taylor_series"]))

register_atom(Atom(atom_type="formula", name="sequence_limit", content="A sequence {a_n} converges to L if for every epsilon>0, there exists N such that |a_n - L| < epsilon for all n > N. Common limits: lim (1+1/n)^n = e, lim n^{1/n} = 1, lim x^n = 0 for |x|<1.", example="a_n = (3n+1)/(2n+5). lim = 3/2 (ratio of leading coefficients). For epsilon=0.01, need |a_n-1.5|<0.01 -> n > 345.", tier=4, domain="sequences", source="Wikipedia contributors, 'Limit of a sequence', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Limit_of_a_sequence", prerequisites=["limit"]))

register_atom(Atom(atom_type="formula", name="fibonacci_properties", content="Fibonacci properties: F(n) ~ phi^n/sqrt(5) (Binet). Cassini's identity: F(n-1)*F(n+1) - F(n)^2 = (-1)^n. Addition formula: F(m+n) = F(m)*F(n+1) + F(m-1)*F(n). GCD property: gcd(F(m),F(n)) = F(gcd(m,n)). Pisano period: F(n) mod m is periodic.", example="F(10)=55. Binet: phi^10/sqrt(5) = 122.99/2.236 = 55.0. Cassini: F(9)*F(11)-F(10)^2 = 34*89-3025 = 3026-3025 = 1 = (-1)^10.", tier=5, domain="sequences", source="Wikipedia contributors, 'Fibonacci number', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Fibonacci_number#Identities", prerequisites=["fibonacci"]))

# ---------------------------------------------------------------------------
# Measure theory ext, model_theory, category_ext, convex_optimization,
# numerical_linalg, numerical_ext2, actuarial, medical_imaging,
# cell_biology_ext, geology_ext, linguistics, linguistics_ext,
# measurement_ext, meta_reasoning_ext2, info_theory_ext,
# info_theory_deep, nuclear_ext
# ---------------------------------------------------------------------------

# Measure ext (tier 6-7)
register_atom(Atom(atom_type="concept", name="outer_measure", content="An outer measure mu* is a set function defined on all subsets with: mu*(empty)=0, monotonicity, countable subadditivity: mu*(union A_i) <= sum mu*(A_i). Lebesgue outer measure of A in R: mu*(A) = inf{sum length(I_k) : A subset union I_k}. Caratheodory's criterion defines measurable sets.", example="A = {1/n : n >= 1}. Cover by intervals [1/n-epsilon/2^n, 1/n+epsilon/2^n]. mu*(A) <= sum epsilon/2^{n-1} = 2*epsilon -> mu*(A)=0.", tier=6, domain="measure_theory", source="Wikipedia contributors, 'Outer measure', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Outer_measure", prerequisites=["summation"]))

register_atom(Atom(atom_type="concept", name="product_measure", content="Given measure spaces (X,mu) and (Y,nu), the product measure mu x nu on X x Y satisfies (mu x nu)(A x B) = mu(A)*nu(B) for measurable rectangles. Fubini's theorem: integral of f over X x Y equals the iterated integral in either order (when f is integrable).", example="X=[0,1] with Lebesgue, Y=[0,1] with Lebesgue. (mu x nu)([0,0.5] x [0,0.3]) = 0.5 * 0.3 = 0.15.", tier=7, domain="measure_theory", source="Wikipedia contributors, 'Product measure', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Product_measure", prerequisites=["fubini_compute"]))

register_atom(Atom(atom_type="theorem", name="radon_nikodym", content="The Radon-Nikodym theorem: if nu is absolutely continuous w.r.t. mu (nu << mu), there exists a measurable function f (the Radon-Nikodym derivative dnu/dmu) such that nu(A) = integral_A f dmu. f is unique a.e. This generalises probability density functions.", example="mu = Lebesgue measure, nu({A}) = integral_A 2x dx. Then dnu/dmu = f(x) = 2x.", tier=7, domain="measure_theory", source="Wikipedia contributors, 'Radon-Nikodym theorem', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Radon%E2%80%93Nikodym_theorem", prerequisites=["dominated_convergence"]))

register_atom(Atom(atom_type="concept", name="convergence_modes", content="Modes of convergence for sequences of functions: pointwise (f_n(x)->f(x) for each x), uniform (sup|f_n-f|->0), in L^p (integral|f_n-f|^p->0), in measure (mu({|f_n-f|>epsilon})->0), almost everywhere (f_n->f except on measure-0 set). Implications: uniform -> pointwise -> a.e. -> in measure. L^p -> in measure.", example="f_n(x) = x^n on [0,1]. Pointwise: f_n->0 for x<1, f_n(1)=1. Converges a.e. but not uniformly.", tier=7, domain="measure_theory", source="Wikipedia contributors, 'Modes of convergence', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Modes_of_convergence", prerequisites=["uniform_convergence"]))

register_atom(Atom(atom_type="concept", name="probability_measure", content="A probability measure P on (Omega, F) satisfies: P(Omega)=1, P(A)>=0, countable additivity: P(union A_i) = sum P(A_i) for disjoint A_i. Properties: P(A^c) = 1-P(A), P(A union B) = P(A)+P(B)-P(A intersect B). Borel probability measures on R are characterised by their CDF.", example="Fair die: Omega={1,...,6}, P({k})=1/6. P(even)=P({2,4,6})=1/2.", tier=5, domain="measure_theory", source="Wikipedia contributors, 'Probability measure', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Probability_measure", prerequisites=["basic_prob"]))

register_atom(Atom(atom_type="formula", name="conditional_expectation_measure", content="The conditional expectation E[X|G] is the G-measurable function satisfying integral_A E[X|G] dP = integral_A X dP for all A in G. For discrete G = sigma({B_1,...,B_n}): E[X|G] = sum (E[X*1_{B_i}]/P(B_i)) * 1_{B_i}.", example="X uniform on [0,1], G = sigma({[0,0.5], (0.5,1]}). E[X|G] = 0.25 on [0,0.5], 0.75 on (0.5,1].", tier=7, domain="measure_theory", source="Wikipedia contributors, 'Conditional expectation', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Conditional_expectation", prerequisites=["radon_nikodym"]))

# Model theory (tier 7-8)
register_atom(Atom(atom_type="concept", name="structure_check", content="A structure M = (A, ...) interprets the symbols of a first-order language: constants as elements, function symbols as functions, relation symbols as relations. A sentence phi is true in M (M |= phi) if it holds under this interpretation.", example="M = (Z, +, *, 0, 1). The sentence 'forall x exists y (x+y=0)' is true in M (additive inverses exist).", tier=7, domain="logic", source="Wikipedia contributors, 'Structure (mathematical logic)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Structure_(mathematical_logic)", prerequisites=["predicate_logic_validity"]))

register_atom(Atom(atom_type="concept", name="elementary_equivalence", content="Two structures M and N are elementarily equivalent (M equiv N) if they satisfy exactly the same first-order sentences. Isomorphic structures are elementarily equivalent, but not conversely (e.g., (Q,<) equiv (R,<) as dense linear orders without endpoints, but not isomorphic).", example="(Q,<) and (R,<): both are dense linear orders without endpoints. Any first-order sentence true in one is true in the other.", tier=7, domain="logic", source="Wikipedia contributors, 'Elementary equivalence', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Elementary_equivalence", prerequisites=["structure_check"]))

register_atom(Atom(atom_type="concept", name="definability", content="A set S is definable in a structure M if there is a formula phi(x) such that S = {a in M : M |= phi(a)}. With parameters: phi(x, b) for fixed b. Example: even numbers are definable in (Z,+,0) by 'exists y (x = y+y)'. The reals have no definable well-ordering.", example="In (N, +, *, 0, 1): primes are definable by 'x>1 and forall y forall z (x=y*z -> y=1 or z=1)'.", tier=7, domain="logic", source="Wikipedia contributors, 'Definable set', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Definable_set", prerequisites=["structure_check"]))

register_atom(Atom(atom_type="theorem", name="compactness_apply", content="The compactness theorem: a set of first-order sentences is satisfiable iff every finite subset is satisfiable. Applications: (1) if every finite substructure has property P, the structure has P (if P is FO-axiomatisable), (2) non-standard models exist (add constants c_n with c_n > n).", example="Axioms for infinite sets: add sentences phi_n = 'there exist n distinct elements' for each n. Every finite subset is satisfiable. By compactness, all together are satisfiable -> infinite model exists.", tier=8, domain="logic", source="Wikipedia contributors, 'Compactness theorem', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Compactness_theorem", prerequisites=["structure_check"]))

register_atom(Atom(atom_type="concept", name="ultraproduct", content="An ultraproduct of structures M_i (i in I) with ultrafilter U on I is the quotient of the direct product by the equivalence relation: (a_i) ~ (b_i) iff {i : a_i = b_i} in U. Los's theorem: the ultraproduct satisfies phi iff {i : M_i |= phi} in U. Produces models with new properties.", example="Ultraproduct of (Z/nZ) with non-principal ultrafilter on N gives a field of characteristic 0 (each prime divides only finitely many n's).", tier=8, domain="logic", source="Wikipedia contributors, 'Ultraproduct', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Ultraproduct", prerequisites=["compactness_apply"]))

# Category ext (tier 7-8)
register_atom(Atom(atom_type="concept", name="monad_compute", content="A monad on a category C is a triple (T, eta, mu) where T: C->C is an endofunctor, eta: Id->T is the unit, and mu: T^2->T is multiplication, satisfying mu . T(mu) = mu . mu_T and mu . eta_T = mu . T(eta) = id. In programming: T = type constructor, eta = return, mu = join.", example="Maybe monad: T(A) = A + {Nothing}. return(a) = Just(a). join(Just(Just(a))) = Just(a), join(Nothing) = Nothing.", tier=7, domain="category_theory", source="Wikipedia contributors, 'Monad (category theory)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Monad_(category_theory)", prerequisites=["functor_apply"]))

register_atom(Atom(atom_type="concept", name="kan_extension", content="A Kan extension of a functor F: C->E along K: C->D is the best approximation of F that factors through K. Left Kan extension Lan_K F: for each d in D, (Lan_K F)(d) = colim_{(c,f:Kc->d)} F(c). Right Kan: limit. Every limit/colimit is a Kan extension. 'All concepts are Kan extensions' (Mac Lane).", example="F: {*}->Set with F(*)=A, K: {*}->N (inclusion as 0). Left Kan of F along K: constant functor sending each n to A (the free extension).", tier=8, domain="category_theory", source="Wikipedia contributors, 'Kan extension', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Kan_extension", prerequisites=["limit_compute"]))

register_atom(Atom(atom_type="concept", name="enriched_category", content="A V-enriched category has hom-objects Hom(A,B) in a monoidal category V (instead of sets). Composition is a morphism in V: Hom(B,C) tensor Hom(A,B) -> Hom(A,C). Examples: Ab-enriched (abelian groups), Top-enriched (topological spaces), [0,inf]-enriched (metric spaces as enriched categories).", example="Metric space as [0,inf]-enriched category: objects = points, Hom(x,y) = d(x,y). Composition = triangle inequality: d(x,z) <= d(x,y)+d(y,z).", tier=7, domain="category_theory", source="Wikipedia contributors, 'Enriched category', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Enriched_category", prerequisites=["morphism_compose"]))

register_atom(Atom(atom_type="concept", name="topos_basics", content="A topos is a category that behaves like the category of sets: has finite limits, exponentials, and a subobject classifier Omega. The subobject classifier generalises {true, false}: Sub(A) ~ Hom(A, Omega). Every Grothendieck topos is a category of sheaves on a site.", example="Set is a topos with Omega = {0,1}. The classifier chi_S: A->{0,1} maps a in S to 1, a not in S to 0.", tier=8, domain="category_theory", source="Wikipedia contributors, 'Topos', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Topos", prerequisites=["monad_compute"]))

register_atom(Atom(atom_type="concept", name="adjunction_unit_counit", content="An adjunction F -| G between categories C and D consists of natural transformations eta: Id_C -> GF (unit) and epsilon: FG -> Id_D (counit) satisfying the triangle identities: (epsilon_F).(F_eta) = id_F and (G_epsilon).(eta_G) = id_G. F is left adjoint, G is right adjoint.", example="Free-forgetful adjunction: F: Set->Grp (free group), G: Grp->Set (underlying set). eta(x) = generator x in F({x}). epsilon maps formal words to their group product.", tier=7, domain="category_theory", source="Wikipedia contributors, 'Adjoint functors', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Adjoint_functors", prerequisites=["natural_transform"]))

register_atom(Atom(atom_type="concept", name="abelian_category", content="An abelian category has: zero object, binary products/coproducts, kernels/cokernels, and every monomorphism is a kernel, every epimorphism is a cokernel. Examples: Ab, R-Mod, sheaves of abelian groups. Homological algebra (exact sequences, derived functors) works in any abelian category.", example="In Ab: kernel of f: A->B is the subgroup {a : f(a)=0}. Cokernel is B/im(f). Short exact sequence: 0->Z->Z->Z/2->0 (multiplication by 2).", tier=7, domain="category_theory", source="Wikipedia contributors, 'Abelian category', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Abelian_category", prerequisites=["exact_sequence"]))

# Convex optimization (tier 6)
register_atom(Atom(atom_type="formula", name="convex_conjugate", content="The convex conjugate (Fenchel conjugate) of f is f*(y) = sup_x(y^T x - f(x)). Properties: f** = f (if f is closed convex), (f+g)* involves infimal convolution. The conjugate of ||x||^2/2 is ||y||^2/2.", example="f(x) = x^2/2. f*(y) = sup_x(xy - x^2/2). Setting derivative to 0: y-x=0, x=y. f*(y) = y^2 - y^2/2 = y^2/2.", tier=6, domain="optimization", source="Wikipedia contributors, 'Convex conjugate', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Convex_conjugate", prerequisites=["derivative"]))

register_atom(Atom(atom_type="algorithm", name="proximal_operator", content="The proximal operator prox_{tf}(v) = argmin_x(f(x) + (1/2t)||x-v||^2). For f=||x||_1: soft thresholding prox(v)_i = sign(v_i)*max(|v_i|-t, 0). Proximal gradient descent: x_{k+1} = prox_{t_k g}(x_k - t_k * grad f(x_k)), for minimising f+g.", example="f = ||x||_1, t=0.5, v=[2,-0.3,1]. prox(v) = [1.5, 0, 0.5]. Values shrunk toward zero.", tier=6, domain="optimization", source="Wikipedia contributors, 'Proximal operator', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Proximal_operator", prerequisites=["gradient_descent"]))

register_atom(Atom(atom_type="theorem", name="strong_duality", content="Strong duality: the optimal values of the primal and dual problems are equal (zero duality gap). Holds for convex problems satisfying Slater's condition (a strictly feasible point exists). KKT conditions are necessary and sufficient at optimality.", example="min x^2 s.t. x >= 1. Dual: max lambda*(1) - lambda^2/4. Primal opt: x*=1, f*=1. Dual opt: lambda*=2, g*=1. Zero gap.", tier=6, domain="optimization", source="Wikipedia contributors, 'Strong duality', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Strong_duality", prerequisites=["dual_lp"]))

register_atom(Atom(atom_type="algorithm", name="subgradient", content="A subgradient of a convex function f at x is any g such that f(y) >= f(x) + g^T(y-x) for all y. The subdifferential df(x) is the set of all subgradients. Subgradient method: x_{k+1} = x_k - alpha_k * g_k. Converges with diminishing step sizes (alpha_k -> 0, sum alpha_k = inf).", example="f(x) = |x|. At x=0: subdifferential = [-1,1]. At x>0: df = {1}. Subgradient step from x=0 with g=0.5: x_1 = -0.5*alpha.", tier=6, domain="optimization", source="Wikipedia contributors, 'Subgradient method', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Subgradient_method", prerequisites=["gradient_descent"]))

register_atom(Atom(atom_type="algorithm", name="barrier_method", content="Interior point / barrier method: approximate constraints by adding a barrier -t*sum(log(-f_i(x))) to the objective, increasing t to tighten the approximation. Each barrier subproblem solved by Newton's method. Central path x*(t) converges to optimal as t->inf. Complexity: O(sqrt(m)*log(1/epsilon)) Newton steps.", example="min c^T x s.t. Ax<=b. Barrier: min c^T x - (1/t)*sum log(b_i - a_i^T x). t=1: loose. t=100: tight. Solve for increasing t.", tier=6, domain="optimization", source="Wikipedia contributors, 'Interior-point method', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Interior-point_method", prerequisites=["newton_raphson"]))

# Nuclear ext (tier 5)
register_atom(Atom(atom_type="formula", name="activity", content="Radioactive activity A = lambda*N = A_0*exp(-lambda*t), where lambda = ln(2)/t_half is the decay constant and N is the number of undecayed atoms. Units: Becquerel (Bq) = 1 disintegration/s. Curie (Ci) = 3.7e10 Bq.", example="N = 1e20 atoms, t_half = 5 years. lambda = ln(2)/5 = 0.1386 yr^{-1}. A = 0.1386 * 1e20 = 1.386e19 yr^{-1} = 4.394e11 Bq.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Radioactive decay', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Radioactive_decay#Activity", prerequisites=["radioactive_decay"]))

register_atom(Atom(atom_type="formula", name="carbon_dating", content="Carbon-14 dating: living organisms maintain C-14/C-12 ratio equal to atmospheric level. After death, C-14 decays (t_half = 5730 years). Age t = -5730/ln(2) * ln(A/A_0), where A/A_0 is the remaining fraction of C-14.", example="Sample has 25% of original C-14. t = -5730/0.693 * ln(0.25) = -8267 * (-1.386) = 11460 years.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Radiocarbon dating', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Radiocarbon_dating", prerequisites=["half_life"]))

register_atom(Atom(atom_type="formula", name="nuclear_fission", content="Nuclear fission splits a heavy nucleus into lighter fragments, releasing energy from the mass defect: E = (m_reactants - m_products)*c^2. U-235 + neutron -> Kr-92 + Ba-141 + 3 neutrons + ~200 MeV. Critical mass depends on geometry, enrichment, and moderator.", example="U-235 fission: mass defect ~ 0.215 u. E = 0.215 * 931.5 MeV/u = 200.3 MeV per fission.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Nuclear fission', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Nuclear_fission", prerequisites=["mass_defect"]))

register_atom(Atom(atom_type="formula", name="nuclear_fusion", content="Nuclear fusion combines light nuclei, releasing energy. D + T -> He-4 + n + 17.6 MeV. Requires overcoming Coulomb barrier (temperature > 10^7 K). Lawson criterion for self-sustaining fusion: n*tau_E > 10^{20} m^{-3} s (for D-T at 10 keV).", example="D-T fusion: mass defect = (2.014+3.016) - (4.003+1.009) = 0.018 u. E = 0.018 * 931.5 = 16.77 MeV.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Nuclear fusion', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Nuclear_fusion", prerequisites=["mass_defect"]))

register_atom(Atom(atom_type="formula", name="dose_calculation", content="Radiation dose: absorbed dose D = energy deposited / mass (Gray, Gy = J/kg). Equivalent dose H = D * w_R, where w_R is radiation weighting factor (1 for gamma/beta, 20 for alpha). Effective dose E = sum(H_T * w_T) where w_T is tissue weighting factor.", example="1 Gy gamma radiation to whole body: H = 1*1 = 1 Sv. 0.1 Gy alpha particles: H = 0.1*20 = 2 Sv (much more damaging).", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Radiation dose', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Absorbed_dose", prerequisites=["division"]))

register_atom(Atom(atom_type="concept", name="neutron_moderation", content="Neutron moderation slows fast neutrons (MeV) to thermal energies (~0.025 eV) for efficient fission. Moderators: light nuclei (H2O, D2O, graphite) with high scattering and low absorption cross sections. Average energy loss per collision: delta E/E = 2A/(A+1)^2, where A is moderator mass number.", example="Hydrogen (A=1): delta E/E = 2/4 = 0.5. Loses 50% energy per collision. ~18 collisions to thermalise 2 MeV neutron.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Neutron moderator', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Neutron_moderator", prerequisites=["mass_defect"]))

# Remaining small modules: actuarial, medical imaging, cell biology ext,
# geology ext, linguistics, linguistics ext, measurement ext,
# meta_reasoning_ext2, info_theory_ext, info_theory_deep, numerical_linalg, numerical_ext2
# These are handled with brief atoms to complete coverage.

# Actuarial (tier 5)
register_atom(Atom(atom_type="formula", name="life_table_actuarial", content="A life table gives survival probabilities. q_x = probability of dying between age x and x+1. l_x = number surviving to age x. d_x = l_x - l_{x+1} = deaths at age x. q_x = d_x/l_x. Life expectancy: e_x = sum l_{x+k}/l_x for k=1,2,...", example="l_60=8000, l_61=7800, l_62=7550. q_60=200/8000=0.025. d_60=200.", tier=5, domain="actuarial", source="Wikipedia contributors, 'Life table', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Life_table", prerequisites=["division"]))

register_atom(Atom(atom_type="formula", name="annuity_pv", content="Present value of annuity: PV = PMT * (1-(1+r)^{-n})/r, where PMT is periodic payment, r is interest rate per period, n is number of periods. Annuity due: PV_due = PV * (1+r). Perpetuity (n->inf): PV = PMT/r.", example="PMT=1000/yr, r=5%, n=20. PV = 1000*(1-1.05^{-20})/0.05 = 1000*12.462 = 12462.", tier=5, domain="actuarial", source="Wikipedia contributors, 'Annuity', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Annuity#Present_value", prerequisites=["compound_interest"]))

register_atom(Atom(atom_type="formula", name="insurance_premium", content="Net single premium = sum of expected present values of benefits. For a whole life insurance on (x): A_x = sum v^{k+1}*k|q_x, where v=1/(1+i) is discount factor, k|q_x = probability of dying at age x+k. Premium = A_x / annuity factor.", example="i=5%, q_60=0.02, q_61=0.03. A_60 ~ 0.02*v + 0.98*0.03*v^2 + ... = 0.019 + 0.027 + ...", tier=5, domain="actuarial", source="Wikipedia contributors, 'Actuarial present value', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Actuarial_present_value", prerequisites=["annuity_pv"]))

register_atom(Atom(atom_type="formula", name="loss_distribution", content="Aggregate loss S = X_1 + ... + X_N where N is claim frequency (Poisson/negative binomial) and X_i is claim severity (lognormal/Pareto). E[S] = E[N]*E[X]. Var[S] = E[N]*Var[X] + Var[N]*(E[X])^2 (compound distribution).", example="N~Poisson(100), X~Exp(mean=5000). E[S]=500000. Var[S]=100*25e6+100*25e6=5e9. SD=70711.", tier=5, domain="actuarial", source="Wikipedia contributors, 'Compound Poisson process', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Compound_Poisson_process", prerequisites=["expected_value"]))

register_atom(Atom(atom_type="formula", name="compound_poisson", content="A compound Poisson process S(t) = sum_{i=1}^{N(t)} X_i, where N(t)~Poisson(lambda*t) and X_i are iid. E[S(t)]=lambda*t*E[X]. Var[S(t)]=lambda*t*E[X^2]. MGF: M_S(s) = exp(lambda*t*(M_X(s)-1)).", example="Claims: lambda=10/year, X~Exp(mean=1000). E[S(1)]=10000. Var[S(1)]=10*2e6=2e7.", tier=6, domain="actuarial", source="Wikipedia contributors, 'Compound Poisson process', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Compound_Poisson_process", prerequisites=["poisson_process"]))

register_atom(Atom(atom_type="formula", name="reserve_calculation", content="Insurance reserve V_t is the expected present value of future benefits minus future premiums at time t. Prospective: V_t = A_{x+t} - P*a_{x+t}. Retrospective: V_t = (P*a_{x:t} - A_{x:t}^1) * (1+i)^t / (l_{x+t}/l_x). Must be positive for solvency.", example="A_{65}=0.6, annual premium P=0.03, annuity a_{65}=10. V_0 = 0.6 - 0.03*10 = 0.3.", tier=6, domain="actuarial", source="Wikipedia contributors, 'Actuarial reserves', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Actuarial_reserves", prerequisites=["insurance_premium"]))

# Medical imaging (tier 5)
register_atom(Atom(atom_type="formula", name="ct_backprojection", content="CT reconstruction from projections uses filtered backprojection: f(x,y) = integral_0^pi [p(theta, x*cos(theta)+y*sin(theta)) * h] d(theta), where p is the filtered projection (Radon transform filtered with ramp filter h). Fourier slice theorem connects projections to 2D Fourier transform.", example="180 projections at 1-degree intervals. Each pixel accumulates contributions from all projection angles passing through it.", tier=5, domain="medical_imaging", source="Wikipedia contributors, 'Radon transform', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Radon_transform", prerequisites=["fourier_transform_pde"]))

register_atom(Atom(atom_type="formula", name="mri_signal", content="MRI signal depends on proton density, T1 (spin-lattice relaxation), and T2 (spin-spin relaxation). Spin echo signal: S = M_0 * (1-exp(-TR/T1)) * exp(-TE/T2), where TR is repetition time and TE is echo time. T1-weighted: short TR/TE. T2-weighted: long TR/TE.", example="Brain tissue: T1=1000ms, T2=80ms. TR=500ms, TE=20ms. S/M_0 = (1-exp(-0.5))*exp(-0.25) = 0.393*0.779 = 0.306.", tier=5, domain="medical_imaging", source="Wikipedia contributors, 'Magnetic resonance imaging', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Magnetic_resonance_imaging#MRI_contrast", prerequisites=["exponentiation"]))

register_atom(Atom(atom_type="algorithm", name="image_convolution", content="2D image convolution: output(x,y) = sum_{i,j} image(x-i, y-j) * kernel(i,j). Common kernels: blur (1/9 * ones(3,3)), edge detection (Sobel, Laplacian), sharpen. Computational cost O(M*N*K^2) for M*N image with K*K kernel. FFT convolution for large kernels.", example="3x3 blur kernel on 5x5 image: each output pixel is the average of its 3x3 neighbourhood.", tier=5, domain="medical_imaging", source="Wikipedia contributors, 'Kernel (image processing)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Kernel_(image_processing)", prerequisites=["matrix_multiply"]))

register_atom(Atom(atom_type="concept", name="fourier_kspace", content="In MRI, k-space is the spatial frequency domain. Each point in k-space is acquired by applying gradients. The image is obtained by 2D inverse Fourier transform of k-space. Centre of k-space = contrast/signal, edges = detail/resolution. Partial k-space sampling accelerates acquisition.", example="256x256 k-space matrix. Centre filled first (low frequencies). Apply 2D IFFT -> 256x256 anatomical image.", tier=5, domain="medical_imaging", source="Wikipedia contributors, 'K-space (magnetic resonance imaging)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/K-space_(MRI)", prerequisites=["fourier_transform_pde"]))

register_atom(Atom(atom_type="formula", name="snr_calculation", content="Signal-to-noise ratio in imaging: SNR = signal / noise_std. For MRI: SNR proportional to voxel_volume * sqrt(N_averages) / sqrt(bandwidth). Doubling resolution (halving voxel size in each dimension) reduces SNR by 8x (or sqrt(8) with 2D).", example="Signal = 500, noise std = 25. SNR = 500/25 = 20. Doubling averages: SNR = 20*sqrt(2) = 28.3.", tier=5, domain="medical_imaging", source="Wikipedia contributors, 'Signal-to-noise ratio', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Signal-to-noise_ratio_(imaging)", prerequisites=["std_dev"]))

register_atom(Atom(atom_type="formula", name="hounsfield_unit", content="Hounsfield units (HU) in CT: HU = 1000 * (mu - mu_water) / (mu_water - mu_air), where mu is the linear attenuation coefficient. Water = 0 HU, air = -1000 HU, bone = +1000 HU. Windowing adjusts display range for different tissues.", example="mu = 0.025 cm^{-1}, mu_water = 0.019, mu_air ~ 0. HU = 1000*(0.025-0.019)/(0.019-0) = 316 (soft tissue).", tier=5, domain="medical_imaging", source="Wikipedia contributors, 'Hounsfield scale', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Hounsfield_scale", prerequisites=["division"]))

# Info theory ext (tier 6)
register_atom(Atom(atom_type="formula", name="conditional_entropy", content="Conditional entropy H(Y|X) = -sum P(x,y)*log P(y|x) = H(X,Y) - H(X). Measures uncertainty in Y given knowledge of X. Chain rule: H(X,Y) = H(X) + H(Y|X). Mutual information I(X;Y) = H(Y) - H(Y|X).", example="X,Y binary: P(0,0)=0.4, P(0,1)=0.1, P(1,0)=0.1, P(1,1)=0.4. H(Y|X) = 0.5*H(0.8,0.2) + 0.5*H(0.2,0.8) = 0.722 bits.", tier=6, domain="information_theory", source="Wikipedia contributors, 'Conditional entropy', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Conditional_entropy", prerequisites=["info_entropy"]))

register_atom(Atom(atom_type="theorem", name="data_processing_inequality", content="Data processing inequality: if X->Y->Z is a Markov chain, then I(X;Z) <= I(X;Y). Processing Y to get Z can only lose information about X, never gain it. Equality iff Z is a sufficient statistic for X.", example="X = original image, Y = compressed, Z = decompressed. I(X;Z) <= I(X;Y). Lossy compression loses information.", tier=6, domain="information_theory", source="Wikipedia contributors, 'Data processing inequality', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Data_processing_inequality", prerequisites=["conditional_entropy"]))

register_atom(Atom(atom_type="formula", name="rate_distortion", content="Rate-distortion theory: the minimum rate R(D) to describe a source with average distortion <= D. For Gaussian source with MSE distortion: R(D) = max(0, 0.5*log(sigma^2/D)). Shannon's source coding theorem: coding at rate R >= R(D) achieves distortion D.", example="Gaussian source, sigma^2=4, D=1. R(1) = 0.5*log(4/1) = 0.5*2 = 1 bit/sample.", tier=6, domain="information_theory", source="Wikipedia contributors, 'Rate-distortion theory', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Rate%E2%80%93distortion_theory", prerequisites=["info_entropy"]))

register_atom(Atom(atom_type="concept", name="typical_set", content="The typical set A_epsilon^n contains sequences x^n whose empirical entropy is close to H(X): 2^{-n(H+epsilon)} <= P(x^n) <= 2^{-n(H-epsilon)}. By AEP, P(A_epsilon^n) > 1-epsilon for large n. |A_epsilon^n| ~ 2^{nH}. Source coding: need nH bits to describe typical sequences.", example="Binary source p=0.1. H=0.469 bits. n=100: |A_epsilon| ~ 2^47 ~ 1.4e14 typical sequences out of 2^100 ~ 1.3e30 total.", tier=6, domain="information_theory", source="Wikipedia contributors, 'Typical set', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Typical_set", prerequisites=["info_entropy"]))

register_atom(Atom(atom_type="theorem", name="kraft_mcmillan", content="Kraft's inequality: a uniquely decodable code exists with word lengths l_1,...,l_n iff sum 2^{-l_i} <= 1. McMillan's theorem: every uniquely decodable code satisfies Kraft's inequality (same as prefix-free codes). Optimal code: l_i ~ -log2(P(x_i)).", example="3 symbols, p=[0.5,0.25,0.25]. Optimal lengths: [1,2,2]. Kraft sum: 0.5+0.25+0.25 = 1. Valid prefix-free code: 0, 10, 11.", tier=5, domain="information_theory", source="Wikipedia contributors, 'Kraft's inequality', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Kraft%27s_inequality", prerequisites=["huffman_coding"]))

register_atom(Atom(atom_type="formula", name="joint_entropy", content="Joint entropy H(X,Y) = -sum P(x,y)*log P(x,y). H(X,Y) <= H(X)+H(Y) with equality iff X and Y are independent. H(X,Y) = H(X) + H(Y|X) = H(Y) + H(X|Y) (chain rule).", example="Independent fair coins: H(X)=1, H(Y)=1. H(X,Y)=2 bits. If X=Y: H(X,Y)=H(X)=1 bit.", tier=5, domain="information_theory", source="Wikipedia contributors, 'Joint entropy', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Joint_entropy", prerequisites=["info_entropy"]))

# Info theory deep (tier 6-7)
register_atom(Atom(atom_type="theorem", name="slepian_wolf", content="Slepian-Wolf theorem: two correlated sources X,Y can be losslessly compressed separately at rates R_X >= H(X|Y), R_Y >= H(Y|X), R_X+R_Y >= H(X,Y). Achieves the same total rate as joint encoding, even when encoders don't communicate.", example="H(X)=H(Y)=1 bit, H(X,Y)=1.5 bits. Joint rate = 1.5. Slepian-Wolf: R_X=1, R_Y=0.5 (or R_X=0.5, R_Y=1).", tier=7, domain="information_theory", source="Wikipedia contributors, 'Slepian-Wolf coding', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Slepian%E2%80%93Wolf_coding", prerequisites=["conditional_entropy"]))

register_atom(Atom(atom_type="formula", name="multiple_access_channel", content="A multiple-access channel has two senders, one receiver. Capacity region: R_1 <= I(X_1;Y|X_2), R_2 <= I(X_2;Y|X_1), R_1+R_2 <= I(X_1,X_2;Y). Achievable via successive decoding or joint decoding.", example="Binary adder channel: Y=X_1+X_2. C_sum = 1.5 bits (3 output levels). Each user can send up to 1 bit if the other sends 0.5 bits.", tier=7, domain="information_theory", source="Wikipedia contributors, 'Multiple-access channel', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Multiple-access_channel_(information_theory)", prerequisites=["channel_capacity"]))

register_atom(Atom(atom_type="formula", name="rate_distortion_binary", content="Rate-distortion for binary source with Hamming distortion: R(D) = H(p) - H(D) for D <= min(p,1-p), else R(D)=0. The source coding theorem: achievable if rate >= R(D). R(0) = H(p) (lossless rate).", example="Binary source p=0.1. R(0.05) = H(0.1)-H(0.05) = 0.469-0.286 = 0.183 bits/symbol. At D=0.1: R=0 (just send all zeros).", tier=6, domain="information_theory", source="Wikipedia contributors, 'Rate-distortion theory', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Rate%E2%80%93distortion_theory#Binary_source", prerequisites=["rate_distortion"]))

register_atom(Atom(atom_type="theorem", name="aep_property", content="The Asymptotic Equipartition Property (AEP): for iid X_1,...,X_n from P(x), -1/n * log P(X_1,...,X_n) -> H(X) in probability. Consequence: most sequences are 'typical' with probability ~ 2^{-nH}. Foundation for source coding: need nH bits.", example="Fair coin (H=1): long sequences have ~n/2 heads. P(sequence) ~ 2^{-n}. Need n bits to encode n coin flips (obvious but proven by AEP).", tier=6, domain="information_theory", source="Wikipedia contributors, 'Asymptotic equipartition property', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Asymptotic_equipartition_property", prerequisites=["info_entropy"]))

register_atom(Atom(atom_type="concept", name="polar_code", content="Polar codes achieve Shannon capacity with efficient encoding and decoding (O(n log n)). Based on channel polarization: as block length n->inf, synthetic channels polarize to either perfectly reliable or completely noisy. Data bits assigned to reliable channels, frozen bits to noisy ones. Successive cancellation decoding.", example="N=8 polar code: 4 data bits on reliable channels, 4 frozen bits (set to 0). Encoding: multiply by generator matrix G = F^{otimes 3} where F=[[1,0],[1,1]].", tier=7, domain="information_theory", source="Wikipedia contributors, 'Polar code (coding theory)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Polar_code_(coding_theory)", prerequisites=["channel_capacity"]))

register_atom(Atom(atom_type="formula", name="entropy_rate", content="The entropy rate of a stochastic process {X_i}: h = lim H(X_n|X_{n-1},...,X_1) = lim H(X_1,...,X_n)/n. For a stationary Markov chain with transition matrix P and stationary distribution pi: h = -sum pi_i * sum P_ij * log P_ij.", example="Binary Markov: P(0|0)=0.9, P(1|1)=0.8. pi=[2/3, 1/3]. h = 2/3*H(0.9,0.1) + 1/3*H(0.8,0.2) = 2/3*0.469 + 1/3*0.722 = 0.554 bits.", tier=6, domain="information_theory", source="Wikipedia contributors, 'Entropy rate', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Entropy_rate", prerequisites=["conditional_entropy"]))

# Linguistics (tier 5)
register_atom(Atom(atom_type="concept", name="chomsky_classify", content="The Chomsky hierarchy classifies formal grammars: Type 0 (unrestricted, Turing machine), Type 1 (context-sensitive, LBA), Type 2 (context-free, PDA), Type 3 (regular, FSA). Each level is a strict subset: regular subset CFL subset CSL subset RE.", example="a^n b^n: CFL (Type 2). a^n b^n c^n: CSL (Type 1). {ww : w in {a,b}*}: CSL.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Chomsky hierarchy', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Chomsky_hierarchy", prerequisites=["cfg_derivation"]))

register_atom(Atom(atom_type="concept", name="morpheme_parse", content="Morphological analysis decomposes words into morphemes: the smallest meaningful units. Free morphemes stand alone (cat, run). Bound morphemes attach to others (un-, -ing, -s). Inflectional: grammatical (walked = walk+ed). Derivational: change meaning/class (un+happy).", example="'unhappiness': un- (prefix, bound) + happy (root, free) + -ness (suffix, bound). 3 morphemes.", tier=4, domain="linguistics", source="Wikipedia contributors, 'Morpheme', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Morpheme", prerequisites=[]))

register_atom(Atom(atom_type="concept", name="syntax_tree", content="A syntax tree (parse tree) represents the hierarchical structure of a sentence according to a grammar. Each internal node is a non-terminal (NP, VP, S). Leaves are terminals (words). Constituency trees vs dependency trees. Ambiguous sentences have multiple parse trees.", example="'The cat sat on the mat': S -> NP VP. NP -> Det N. VP -> V PP. PP -> P NP. The -> Det, cat -> N, sat -> V, on -> P, the -> Det, mat -> N.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Parse tree', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Parse_tree", prerequisites=["cfg_derivation"]))

register_atom(Atom(atom_type="concept", name="phonetic_features", content="Phonetic features classify speech sounds: voicing (+/- voice), place of articulation (bilabial, alveolar, velar, ...), manner (stop, fricative, nasal, ...). IPA encodes sounds systematically. Example features: [p] = voiceless bilabial stop, [b] = voiced bilabial stop, [m] = voiced bilabial nasal.", example="[t]: voiceless alveolar stop. [d]: voiced alveolar stop. [n]: voiced alveolar nasal. [s]: voiceless alveolar fricative.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Distinctive feature', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Distinctive_feature", prerequisites=[]))

register_atom(Atom(atom_type="concept", name="regular_language_check", content="A language L is regular iff it can be described by a regular expression, recognised by a DFA/NFA, or generated by a regular grammar. To prove non-regularity: use the pumping lemma. If for every pumping length p, there exists a string s in L with |s|>=p that cannot be pumped, then L is not regular.", example="L = {a^n b^n}: assume regular with pumping length p. s = a^p b^p. Pumping the a's gives a^{p+k}b^p not in L. Therefore not regular.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Regular language', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Regular_language", prerequisites=["pumping_lemma"]))

# Linguistics ext (tier 5)
register_atom(Atom(atom_type="algorithm", name="syllable_count", content="Syllable counting heuristic for English: count vowel groups (a,e,i,o,u,y). Subtract silent e at end. Subtract for diphthongs (ea, ou, etc.). Minimum 1 syllable. More accurate: use CMU Pronouncing Dictionary for lookup.", example="'computer': vowel groups co-pu-er = 3 syllables. 'smile': s-mi-le, 2 groups, subtract silent e = 1 syllable.", tier=4, domain="linguistics", source="Wikipedia contributors, 'Syllable', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Syllable", prerequisites=[]))

register_atom(Atom(atom_type="concept", name="ipa_transcription", content="The International Phonetic Alphabet (IPA) provides a unique symbol for each speech sound. Vowels positioned by height (open/close) and backness (front/back). Consonants by place and manner of articulation. Suprasegmentals: stress, tone, intonation.", example="English 'cat': /kaet/ (IPA). 'sheep': /shi:p/. Primary stress marked with apostrophe before stressed syllable.", tier=5, domain="linguistics", source="Wikipedia contributors, 'International Phonetic Alphabet', Wikipedia.", source_url="https://en.wikipedia.org/wiki/International_Phonetic_Alphabet", prerequisites=["phonetic_features"]))

register_atom(Atom(atom_type="concept", name="morphological_analysis", content="Morphological analysis identifies a word's internal structure: root, prefixes, suffixes, inflections. Finite-state transducers model morphological rules: surface form <-> lexical form. Turkish, Finnish, etc. have rich morphology requiring extensive analysis.", example="'unbelievable': un- (negative prefix) + believe (root verb) + -able (adjective suffix). Lexical: UN + BELIEVE + ABLE.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Morphological parsing', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Morphological_parsing", prerequisites=["morpheme_parse"]))

register_atom(Atom(atom_type="formula", name="word_frequency", content="Zipf's law: the frequency of the n-th most common word is proportional to 1/n. Rank * frequency ~ constant. In English, 'the' is ~7% of text, 'of' ~3.5%, 'and' ~2.8%. Top 100 words cover ~50% of text. Long tail of rare words.", example="Corpus of 1M words: rank 1 word ('the') appears ~70000 times. Rank 10 appears ~7000. Rank 100 appears ~700.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Zipf's law', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Zipf%27s_law", prerequisites=["logarithm"]))

register_atom(Atom(atom_type="formula", name="language_entropy", content="The entropy of a language H measures its information density. For English text: H ~ 1.0-1.5 bits/character (Shannon's experiments with human predictors). Redundancy R = 1 - H/H_max, where H_max = log2(27) ~ 4.75 bits/char. English redundancy ~ 70-80%.", example="If H = 1.3 bits/char and H_max = 4.75: R = 1-1.3/4.75 = 0.726 = 72.6% redundancy.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Entropy (information theory)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Entropy_(information_theory)#Entropy_of_natural_languages", prerequisites=["info_entropy"]))

register_atom(Atom(atom_type="algorithm", name="edit_distance_linguistic", content="Edit distance (Levenshtein distance) between two strings is the minimum number of single-character edits (insert, delete, substitute) to transform one into the other. DP algorithm: d[i][j] = min(d[i-1][j]+1, d[i][j-1]+1, d[i-1][j-1]+(0 if s[i]=t[j] else 1)). Used for spell checking, fuzzy matching.", example="'kitten' to 'sitting': k->s (sub), e->i (sub), +g (insert). Distance = 3.", tier=4, domain="linguistics", source="Wikipedia contributors, 'Levenshtein distance', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Levenshtein_distance", prerequisites=["edit_distance"]))

# Cell biology ext (tier 5)
register_atom(Atom(atom_type="concept", name="cell_signaling", content="Cell signalling pathways transmit information from receptors to effectors. Steps: ligand binding -> receptor activation -> signal transduction (kinase cascades, second messengers like cAMP, Ca2+) -> gene expression changes. MAPK pathway: receptor -> Ras -> Raf -> MEK -> ERK -> transcription factors.", example="Insulin signalling: insulin binds receptor -> IRS phosphorylation -> PI3K -> Akt -> GLUT4 translocation -> glucose uptake.", tier=5, domain="cell_biology", source="Wikipedia contributors, 'Cell signaling', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Cell_signaling", prerequisites=[]))

register_atom(Atom(atom_type="concept", name="gene_expression_regulation", content="Gene expression is regulated at multiple levels: transcriptional (promoters, enhancers, transcription factors), post-transcriptional (mRNA stability, miRNA), translational (ribosome binding), post-translational (phosphorylation, ubiquitination). Epigenetic: DNA methylation, histone modification.", example="Lac operon: repressor blocks transcription without lactose. Lactose (allolactose) binds repressor, releases it, allows transcription of lacZ, lacY, lacA.", tier=5, domain="cell_biology", source="Wikipedia contributors, 'Regulation of gene expression', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Regulation_of_gene_expression", prerequisites=[]))

register_atom(Atom(atom_type="concept", name="cell_cycle_checkpoint", content="Cell cycle checkpoints ensure proper division: G1/S (DNA damage check, p53/Rb), intra-S (replication fork monitoring), G2/M (DNA replication complete, CDC2/cyclin B), spindle assembly (all chromosomes attached). Checkpoint failure leads to cancer or apoptosis.", example="G1 checkpoint: DNA damage detected -> p53 activated -> p21 produced -> CDK4/cyclin D inhibited -> cell cycle arrested.", tier=5, domain="cell_biology", source="Wikipedia contributors, 'Cell cycle checkpoint', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Cell_cycle_checkpoint", prerequisites=[]))

register_atom(Atom(atom_type="formula", name="pcr_amplification", content="PCR amplifies DNA exponentially: N = N_0 * 2^n (ideal), where N_0 is initial copies and n is number of cycles. Real efficiency E: N = N_0 * (1+E)^n, where E is typically 0.8-1.0. Ct (cycle threshold) is inversely proportional to log(initial DNA).", example="N_0=100 copies, n=30 cycles, E=0.9. N = 100*(1.9)^30 = 100*2.37e8 = 2.37e10 copies.", tier=5, domain="cell_biology", source="Wikipedia contributors, 'Polymerase chain reaction', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Polymerase_chain_reaction", prerequisites=["exponentiation"]))

register_atom(Atom(atom_type="concept", name="apoptosis_pathway", content="Apoptosis (programmed cell death) occurs via intrinsic (mitochondrial) or extrinsic (death receptor) pathways. Intrinsic: stress -> Bax/Bak -> cytochrome c release -> apoptosome -> caspase-9 -> caspase-3. Extrinsic: Fas/TNF receptor -> DISC -> caspase-8 -> caspase-3. Both converge on executioner caspases.", example="UV damage -> p53 -> Bax expression -> mitochondrial membrane permeabilisation -> cytochrome c -> caspase cascade -> cell death.", tier=5, domain="cell_biology", source="Wikipedia contributors, 'Apoptosis', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Apoptosis", prerequisites=[]))

register_atom(Atom(atom_type="formula", name="receptor_binding", content="Receptor-ligand binding follows the law of mass action: [RL]/[R_total] = [L]/(K_d + [L]), where K_d is the dissociation constant. At [L]=K_d, 50% of receptors are occupied. Scatchard plot: [RL]/[L] = (B_max - [RL])/K_d.", example="K_d = 10 nM, [L] = 30 nM. Fractional occupancy = 30/(10+30) = 0.75. 75% of receptors bound.", tier=5, domain="cell_biology", source="Wikipedia contributors, 'Ligand (biochemistry)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Ligand_(biochemistry)#Binding_affinity", prerequisites=["michaelis_menten"]))

# Geology ext (tier 5)
register_atom(Atom(atom_type="concept", name="mineral_identification", content="Minerals are identified by physical properties: hardness (Mohs scale), lustre (metallic, vitreous), cleavage/fracture, colour, streak, crystal system, specific gravity. Diagnostic tests: HCl fizz (calcite), magnetism (magnetite), taste (halite), fluorescence.", example="Calcite: hardness 3, vitreous lustre, rhombohedral cleavage, fizzes with HCl, white streak.", tier=4, domain="geology", source="Wikipedia contributors, 'Mineral identification', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Mineral_identification", prerequisites=[]))

register_atom(Atom(atom_type="concept", name="rock_cycle", content="The rock cycle describes transformations between igneous, sedimentary, and metamorphic rocks. Igneous (magma cooling) -> weathering/erosion -> sedimentary (compaction/cementation) -> metamorphic (heat/pressure) -> melting -> igneous. Any rock type can transform to any other.", example="Granite (igneous) -> weathers to sand -> sandstone (sedimentary) -> heat/pressure -> quartzite (metamorphic) -> melts -> new igneous.", tier=4, domain="geology", source="Wikipedia contributors, 'Rock cycle', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Rock_cycle", prerequisites=[]))

register_atom(Atom(atom_type="concept", name="stratigraphy", content="Stratigraphy studies rock layers (strata). Principles: superposition (older layers below), original horizontality, lateral continuity, cross-cutting relationships (faults/intrusions are younger than what they cut). Biostratigraphy uses fossils for correlation. Sequence stratigraphy uses sea-level changes.", example="Layer A is cut by fault B, which is covered by layer C. Age order: A (oldest), B (fault), C (youngest).", tier=5, domain="geology", source="Wikipedia contributors, 'Stratigraphy', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Stratigraphy", prerequisites=[]))

register_atom(Atom(atom_type="formula", name="earthquake_energy", content="Earthquake energy from magnitude: log10(E) = 1.5*M + 4.8 (Gutenberg-Richter, E in joules). Each magnitude unit = 31.6x energy. M7 ~ 2e15 J (= 0.5 kilotons TNT). Moment magnitude M_w = (2/3)*log10(M_0) - 10.7, where M_0 is seismic moment in dyne-cm.", example="M=5: E = 10^(7.5+4.8) = 10^12.3 = 2e12 J. M=6: E = 10^13.8 = 6.3e13 J (31.6x more).", tier=5, domain="geology", source="Wikipedia contributors, 'Richter magnitude scale', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Richter_magnitude_scale#Energy_release", prerequisites=["exponentiation"]))

register_atom(Atom(atom_type="concept", name="geologic_time", content="Geologic time scale: Eon > Era > Period > Epoch. Phanerozoic eon (541 Ma-present): Paleozoic (Cambrian-Permian), Mesozoic (Triassic-Cretaceous), Cenozoic (Paleogene-Quaternary). Major events: Cambrian explosion (541 Ma), end-Permian extinction (252 Ma), K-Pg extinction (66 Ma).", example="Dinosaurs lived in the Mesozoic Era (252-66 Ma): Triassic (first dinosaurs), Jurassic (Stegosaurus), Cretaceous (T. rex, ending with K-Pg impact).", tier=4, domain="geology", source="Wikipedia contributors, 'Geologic time scale', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Geologic_time_scale", prerequisites=[]))

register_atom(Atom(atom_type="formula", name="porosity_permeability", content="Porosity phi = V_pore/V_total (fraction of void space). Permeability k (Darcy) measures fluid flow ability: Q = k*A*dP/(mu*L) (Darcy's law). Well-sorted sand: phi~30-40%, k~10-100 Darcy. Clay: phi~40-70%, k~1e-6 Darcy (high porosity but low permeability).", example="Sandstone: phi=0.25, k=1 Darcy, A=1m^2, dP=100 kPa, mu=1 cP, L=10 m. Q = 1e-12*1*1e5/(1e-3*10) = 1e-5 m^3/s.", tier=5, domain="geology", source="Wikipedia contributors, 'Porosity', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Porosity", prerequisites=["division"]))

# Measurement ext (tier 5)
register_atom(Atom(atom_type="formula", name="error_propagation", content="For f(x,y,...) with independent uncertainties: delta_f = sqrt((df/dx*delta_x)^2 + (df/dy*delta_y)^2 + ...). Addition: delta_{x+y} = sqrt(delta_x^2+delta_y^2). Multiplication: delta_{xy}/|xy| = sqrt((delta_x/x)^2+(delta_y/y)^2).", example="f=x*y, x=5.0+/-0.1, y=3.0+/-0.2. delta_f/15 = sqrt((0.1/5)^2+(0.2/3)^2) = sqrt(0.0004+0.0044) = 0.069. f=15.0+/-1.04.", tier=5, domain="measurement", source="Wikipedia contributors, 'Propagation of uncertainty', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Propagation_of_uncertainty", prerequisites=["partial_derivative"]))

register_atom(Atom(atom_type="formula", name="dimensional_analysis_compute", content="Dimensional analysis checks equations by verifying dimensions match. Base dimensions: [M], [L], [T], [I], [Theta], [N], [J]. Buckingham pi theorem: n variables with k fundamental dimensions give n-k dimensionless groups. Used to derive scaling laws.", example="F = m*a. [F] = [M*L*T^{-2}]. [m*a] = [M]*[L*T^{-2}] = [M*L*T^{-2}]. Dimensionally consistent.", tier=4, domain="measurement", source="Wikipedia contributors, 'Dimensional analysis', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Dimensional_analysis", prerequisites=[]))

register_atom(Atom(atom_type="formula", name="significant_figures_calc", content="Significant figures rules: (1) All non-zero digits are significant. (2) Zeros between non-zero digits are significant. (3) Leading zeros are not significant. (4) Trailing zeros after decimal point are significant. Addition: round to fewest decimal places. Multiplication: round to fewest sig figs.", example="3.14159 has 6 sig figs. 0.0045 has 2. 3.14 * 2.1 = 6.6 (2 sig figs). 3.14 + 2.1 = 5.2 (1 decimal place).", tier=4, domain="measurement", source="Wikipedia contributors, 'Significant figures', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Significant_figures", prerequisites=[]))

register_atom(Atom(atom_type="method", name="calibration_curve", content="A calibration curve relates instrument response to known concentrations. Fit y = mx + b (linear regression) to standards. Unknown concentration: x = (y_measured - b)/m. R^2 > 0.99 for good linearity. Limit of detection LOD = 3*sigma_blank/m.", example="Standards: (0,0.01), (10,0.52), (20,1.03), (30,1.54). Slope m=0.051, intercept b=0.01. Unknown y=0.78: x=(0.78-0.01)/0.051=15.1.", tier=5, domain="measurement", source="Wikipedia contributors, 'Calibration curve', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Calibration_curve", prerequisites=["linear_regression"]))

register_atom(Atom(atom_type="concept", name="accuracy_precision", content="Accuracy is closeness to the true value (low systematic error). Precision is closeness of repeated measurements to each other (low random error). High precision + low accuracy = systematic bias. Trueness (ISO) = accuracy. Repeatability = precision under identical conditions.", example="True value = 10.0. Measurements: [10.2, 10.1, 10.3] = accurate and precise. [9.0, 9.1, 8.9] = precise but not accurate (bias of -1).", tier=4, domain="measurement", source="Wikipedia contributors, 'Accuracy and precision', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Accuracy_and_precision", prerequisites=[]))

register_atom(Atom(atom_type="formula", name="logarithmic_scales", content="Logarithmic scales compress wide ranges: decibel dB = 10*log10(P/P_ref) for power, 20*log10(V/V_ref) for amplitude. pH = -log10([H+]). Richter magnitude ~ log10(amplitude). Each unit represents a factor of 10 (power) or sqrt(10) (amplitude).", example="Sound power 100x reference: 10*log10(100) = 20 dB. 1000x: 30 dB. Each 10 dB = 10x power.", tier=4, domain="measurement", source="Wikipedia contributors, 'Logarithmic scale', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Logarithmic_scale", prerequisites=["logarithm"]))

# Meta reasoning ext2 (tier 7-8) - These are classification tasks
register_atom(Atom(atom_type="method", name="proof_strategy", content="Choosing a proof strategy: direct proof (assume premises, derive conclusion), proof by contradiction (assume negation, derive contradiction), proof by induction (base case + inductive step), proof by contrapositive (prove not-Q implies not-P), constructive vs non-constructive.", example="Prove sqrt(2) is irrational: contradiction. Assume p/q in lowest terms, then p^2=2q^2 implies p even, then q even, contradicting lowest terms.", tier=7, domain="meta_reasoning", source="Wikipedia contributors, 'Mathematical proof', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Mathematical_proof", prerequisites=[]))

register_atom(Atom(atom_type="method", name="dimensional_check", content="Dimensional checking verifies formula correctness by ensuring both sides have the same physical dimensions. Each term in a sum must have the same dimensions. Arguments of transcendental functions must be dimensionless. Catches many algebraic errors without computing values.", example="E = mc^2: [E] = [M*L^2*T^{-2}]. [mc^2] = [M]*[L^2*T^{-2}] = [M*L^2*T^{-2}]. Consistent.", tier=7, domain="meta_reasoning", source="Wikipedia contributors, 'Dimensional analysis', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Dimensional_analysis", prerequisites=[]))

register_atom(Atom(atom_type="method", name="approximation_bound", content="An approximation bound quantifies how close an approximate solution is to optimal. Additive: |f(x_approx) - f(x*)| <= epsilon. Multiplicative: f(x_approx) <= alpha*f(x*) (alpha-approximation). PTAS: alpha = 1+epsilon for any epsilon > 0. APX: constant-factor approximation.", example="Greedy set cover: ln(n)-approximation. For n=100: solution is at most ln(100) ~ 4.6 times optimal.", tier=7, domain="meta_reasoning", source="Wikipedia contributors, 'Approximation algorithm', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Approximation_algorithm", prerequisites=[]))

register_atom(Atom(atom_type="concept", name="research_methodology", content="Scientific research methodology: (1) observe phenomenon, (2) formulate hypothesis, (3) design experiment (control group, randomisation, blinding), (4) collect data, (5) analyse (statistical tests), (6) draw conclusions, (7) peer review and publish. Null hypothesis testing, p-values, effect sizes.", example="Hypothesis: drug X lowers blood pressure. RCT: 100 patients randomised to drug/placebo. Measure BP at 12 weeks. t-test p=0.003 -> reject null.", tier=8, domain="meta_reasoning", source="Wikipedia contributors, 'Scientific method', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Scientific_method", prerequisites=[]))

register_atom(Atom(atom_type="concept", name="theorem_dependency", content="Theorem dependency analysis identifies which axioms, definitions, and prior theorems a result depends on. Dependency graph is a DAG. Removing a dependency may invalidate the theorem. Minimal dependencies = strongest result. Used in formal verification and proof assistants (Coq, Lean).", example="Fundamental theorem of calculus depends on: Riemann integral definition, Mean Value Theorem, limit definition. MVT depends on Rolle's theorem, which depends on Extreme Value Theorem.", tier=8, domain="meta_reasoning", source="Wikipedia contributors, 'Mathematical proof', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Mathematical_proof#Structure", prerequisites=[]))

# Numerical linear algebra (tier 6)
register_atom(Atom(atom_type="algorithm", name="qr_decomposition", content="QR decomposition factors A = QR where Q is orthogonal and R is upper triangular. Methods: Gram-Schmidt (numerically unstable), Modified Gram-Schmidt, Householder reflections (stable, O(2mn^2/3) flops). Used for least squares, eigenvalue computation (QR algorithm).", example="A=[[1,1],[1,-1]]. Gram-Schmidt: q1=[1,1]/sqrt(2), q2=[1,-1]/sqrt(2). R=[[sqrt(2),0],[0,sqrt(2)]].", tier=6, domain="numerical_analysis", source="Wikipedia contributors, 'QR decomposition', Wikipedia.", source_url="https://en.wikipedia.org/wiki/QR_decomposition", prerequisites=["gram_schmidt"]))

register_atom(Atom(atom_type="algorithm", name="svd_compute", content="SVD: A = U*Sigma*V^T where U,V are orthogonal, Sigma is diagonal. Sigma contains singular values sigma_1 >= sigma_2 >= ... >= 0. Computed via bidiagonalisation then QR iteration. Rank = number of non-zero singular values. Condition number = sigma_max/sigma_min.", example="A=[[3,2],[2,3]]. SVD: sigma_1=5, sigma_2=1. Condition number = 5. Well-conditioned.", tier=6, domain="numerical_analysis", source="Wikipedia contributors, 'Singular value decomposition', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Singular_value_decomposition", prerequisites=["eigenvalue"]))

register_atom(Atom(atom_type="algorithm", name="cholesky_factor", content="Cholesky decomposition: A = LL^T for symmetric positive definite A, where L is lower triangular. L_ii = sqrt(A_ii - sum_{k<i} L_ik^2). L_ji = (A_ji - sum_{k<j} L_jk*L_ik) / L_jj. Half the cost of LU. Used for solving linear systems, generating correlated random variables.", example="A=[[4,2],[2,5]]. L_11=sqrt(4)=2. L_21=2/2=1. L_22=sqrt(5-1)=2. A = [[2,0],[1,2]]*[[2,1],[0,2]].", tier=6, domain="numerical_analysis", source="Wikipedia contributors, 'Cholesky decomposition', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Cholesky_decomposition", prerequisites=["determinant"]))

register_atom(Atom(atom_type="algorithm", name="jacobi_iteration", content="Jacobi iteration solves Ax=b: x_i^{k+1} = (b_i - sum_{j!=i} a_ij*x_j^k) / a_ii. Converges if A is strictly diagonally dominant (|a_ii| > sum_{j!=i}|a_ij|). Parallel-friendly: each component updates independently. Slower convergence than Gauss-Seidel.", example="[[4,1],[1,3]]x=[5,5]. Jacobi from x=[0,0]: x^1=[1.25, 1.667], x^2=[0.833, 1.25], ... converges to [0.909, 1.364].", tier=5, domain="numerical_analysis", source="Wikipedia contributors, 'Jacobi method', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Jacobi_method", prerequisites=["system_equations"]))

register_atom(Atom(atom_type="algorithm", name="gauss_seidel", content="Gauss-Seidel iteration: x_i^{k+1} = (b_i - sum_{j<i} a_ij*x_j^{k+1} - sum_{j>i} a_ij*x_j^k) / a_ii. Uses updated values immediately (unlike Jacobi). Converges for SPD matrices. Generally faster than Jacobi but not parallelisable.", example="Same system as Jacobi: x^1=[1.25, 1.25], x^2=[0.9375, 1.354], faster convergence.", tier=5, domain="numerical_analysis", source="Wikipedia contributors, 'Gauss-Seidel method', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Gauss%E2%80%93Seidel_method", prerequisites=["jacobi_iteration"]))

register_atom(Atom(atom_type="algorithm", name="least_squares", content="Least squares solves the overdetermined system Ax~b by minimising ||Ax-b||^2. Normal equations: A^T A x = A^T b. Numerically better: use QR decomposition (Rx = Q^T b) or SVD. Pseudoinverse: x = (A^T A)^{-1} A^T b = A^+ b.", example="Points (0,1),(1,3),(2,5). A=[[1,0],[1,1],[1,2]], b=[1,3,5]. Normal eqs: [[3,3],[3,5]]x = [9,13]. x = [1, 2]. Line: y = 1+2x.", tier=5, domain="numerical_analysis", source="Wikipedia contributors, 'Least squares', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Least_squares", prerequisites=["linear_regression"]))

# Numerical ext2 (tier 5-6)
register_atom(Atom(atom_type="algorithm", name="gaussian_quadrature", content="Gaussian quadrature approximates integrals using optimal node placement: integral ~ sum w_i * f(x_i). n-point Gauss-Legendre quadrature is exact for polynomials of degree <= 2n-1. Nodes are roots of Legendre polynomials on [-1,1]. Much more accurate than Newton-Cotes for smooth functions.", example="2-point Gauss-Legendre: nodes x=+/-1/sqrt(3), weights w=1. integral_{-1}^{1} x^3 dx = 1*((-1/sqrt(3))^3) + 1*((1/sqrt(3))^3) = 0. Exact (degree 3 < 2*2-1=3).", tier=6, domain="numerical_analysis", source="Wikipedia contributors, 'Gaussian quadrature', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Gaussian_quadrature", prerequisites=["simpson_rule"]))

register_atom(Atom(atom_type="algorithm", name="adams_bashforth", content="Adams-Bashforth methods are explicit linear multistep methods for ODEs. AB2: y_{n+1} = y_n + h/2*(3*f_n - f_{n-1}). AB4: y_{n+1} = y_n + h/24*(55*f_n - 59*f_{n-1} + 37*f_{n-2} - 9*f_{n-3}). Higher order but needs startup values from a one-step method.", example="y' = y, y(0)=1, h=0.1. AB2 (after Euler startup): y_1=1.1. y_2 = 1.1 + 0.05*(3*1.1 - 1) = 1.1+0.05*2.3 = 1.215.", tier=6, domain="numerical_analysis", source="Wikipedia contributors, 'Linear multistep method', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Linear_multistep_method#Adams%E2%80%93Bashforth_methods", prerequisites=["euler_method_ode"]))

register_atom(Atom(atom_type="algorithm", name="newton_interpolation", content="Newton's divided difference interpolation: p(x) = f[x_0] + f[x_0,x_1]*(x-x_0) + f[x_0,x_1,x_2]*(x-x_0)*(x-x_1) + ... Divided differences: f[x_i,x_{i+1}] = (f[x_{i+1}]-f[x_i])/(x_{i+1}-x_i). Adding a new point only requires computing one new divided difference.", example="Points (1,1),(2,4),(3,9). f[1]=1. f[1,2]=(4-1)/1=3. f[1,2,3]=(f[2,3]-f[1,2])/2=(5-3)/2=1. p(x)=1+3(x-1)+1(x-1)(x-2)=x^2.", tier=5, domain="numerical_analysis", source="Wikipedia contributors, 'Newton's divided differences interpolation formula', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Newton%27s_divided_differences_interpolation_formula", prerequisites=["interpolation_lagrange"]))

register_atom(Atom(atom_type="formula", name="numerical_integration_error", content="Trapezoid rule error: O(h^2) globally, exact for degree 1. Simpson's rule: O(h^4), exact for degree 3. Gaussian quadrature with n points: exact for degree 2n-1. Richardson extrapolation improves accuracy by combining results at different step sizes.", example="Trapezoid with h=0.1: error ~ (b-a)^3/(12*n^2)*f''. Halving h reduces error by 4x. Simpson with h=0.1: error ~ (b-a)^5/(180*n^4)*f''''.", tier=5, domain="numerical_analysis", source="Wikipedia contributors, 'Numerical integration', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Numerical_integration#Error_analysis", prerequisites=["trapezoidal_rule"]))

register_atom(Atom(atom_type="algorithm", name="eigenvalue_power_iteration", content="Power iteration finds the dominant eigenvalue: x_{k+1} = A*x_k / ||A*x_k||. Converges to the eigenvector for the largest |eigenvalue|. Rate: |lambda_2/lambda_1|^k. Inverse iteration (using (A-sigma*I)^{-1}) finds eigenvalue nearest to shift sigma.", example="A=[[2,1],[1,2]]. Start x=[1,0]. Ax=[2,1], normalise=[0.894,0.447]. After iterations converges to [1,1]/sqrt(2), lambda=3.", tier=6, domain="numerical_analysis", source="Wikipedia contributors, 'Power iteration', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Power_iteration", prerequisites=["eigenvalue"]))

register_atom(Atom(atom_type="method", name="nonlinear_system", content="Nonlinear system F(x)=0 solved by Newton's method: x_{k+1} = x_k - J(x_k)^{-1}*F(x_k), where J is the Jacobian matrix. Quadratic convergence near the root. Alternative: Broyden's method (quasi-Newton, avoids computing Jacobian at each step).", example="f1=x^2+y^2-4, f2=x*y-1. J=[[2x,2y],[y,x]]. At (1.5,0.7): F=[0.74,0.05], J=[[3,1.4],[0.7,1.5]]. Newton step: dx = -J^{-1}*F.", tier=6, domain="numerical_analysis", source="Wikipedia contributors, 'Newton's method#Nonlinear_systems', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Newton%27s_method#Nonlinear_systems_of_equations", prerequisites=["newton_raphson"]))
