"""Knowledge atoms for recursion ext, automata deep, and numerical methods ext2."""
from engram_generator.base import Atom
from engram_generator.atoms.registry import register_atom

# -- Recursion ext --
register_atom(Atom(atom_type="algorithm", name="tower_of_hanoi", content="The Tower of Hanoi moves n disks between 3 pegs using the rule: never place a larger disk on a smaller one. Minimum moves: 2^n - 1. Recursive: move n-1 from source to auxiliary, move disk n to target, move n-1 from auxiliary to target.", example="n=3: 2^3-1=7 moves. Sequence: A->C, A->B, C->B, A->C, B->A, B->C, A->C.", tier=4, domain="recursion", source="Wikipedia contributors, 'Tower of Hanoi', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Tower_of_Hanoi", prerequisites=["exponentiation"]))
register_atom(Atom(atom_type="algorithm", name="recursive_power", content="Recursive exponentiation computes x^n by: x^0=1, x^n=x*x^(n-1) for n>0. Fast exponentiation: x^n=(x^(n/2))^2 if n even, x*x^(n-1) if n odd. Time: O(log n) multiplications.", example="2^10: 2^10=(2^5)^2, 2^5=2*(2^2)^2, 2^2=(2^1)^2=4. So 2^5=2*16=32, 2^10=1024. 4 multiplications.", tier=4, domain="recursion", source="Wikipedia contributors, 'Exponentiation by squaring', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Exponentiation_by_squaring", prerequisites=["exponentiation"]))
register_atom(Atom(atom_type="algorithm", name="recursive_gcd", content="Euclid's algorithm computes gcd(a, b) recursively: gcd(a, 0) = a, gcd(a, b) = gcd(b, a mod b). Each step reduces the problem size by at least half, giving O(log(min(a,b))) divisions.", example="gcd(48, 18): gcd(48,18)=gcd(18,12)=gcd(12,6)=gcd(6,0)=6. Three recursive calls.", tier=4, domain="recursion", source="Wikipedia contributors, 'Euclidean algorithm', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Euclidean_algorithm", prerequisites=["gcd"]))
register_atom(Atom(atom_type="algorithm", name="recursive_binary_search", content="Binary search recursively halves the search space: compare target with middle element, recurse on left or right half. Base case: empty range or target found. Time: O(log n), space O(log n) for recursive stack.", example="Array [2,4,7,10,15], target=7. Mid=7, found at index 2. 1 comparison.", tier=4, domain="recursion", source="Wikipedia contributors, 'Binary search algorithm', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Binary_search_algorithm", prerequisites=["division"]))
register_atom(Atom(atom_type="algorithm", name="recursive_sum", content="Recursive summation: sum(arr, n) = arr[n-1] + sum(arr, n-1), with base case sum(arr, 0) = 0. Demonstrates that any iterative computation can be expressed recursively. Tail recursion optimisation converts to iteration.", example="sum([3, 5, 2, 8]): sum(4)=8+sum(3)=8+2+sum(2)=8+2+5+sum(1)=8+2+5+3=18.", tier=4, domain="recursion", source="Wikipedia contributors, 'Recursion (computer science)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Recursion_(computer_science)", prerequisites=["summation"]))
register_atom(Atom(atom_type="algorithm", name="recursive_permutations", content="Generating permutations recursively: fix each element at position 0 and recurse on the remaining elements. For n elements: n! permutations. Heap's algorithm generates all permutations with O(n!) swaps.", example="Permutations of [1,2,3]: fix 1 -> perm([2,3]) = [1,2,3],[1,3,2]. fix 2 -> [2,1,3],[2,3,1]. fix 3 -> [3,1,2],[3,2,1]. Total: 6 = 3!.", tier=4, domain="recursion", source="Wikipedia contributors, 'Heap's algorithm', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Heap%27s_algorithm", prerequisites=["permutation"]))

# -- Automata deep --
register_atom(Atom(atom_type="algorithm", name="dfa_complement", content="The complement of a DFA accepts exactly the strings the original rejects. Construction: swap accepting and non-accepting states. If L(M) has accept states F, then L(complement(M)) has accept states Q - F. Requires the DFA to be complete (transitions for all inputs at all states).", example="DFA over {0,1} with states {q0, q1}, F={q0}: accepts even-length strings. Complement F'={q1}: accepts odd-length strings.", tier=5, domain="automata_theory", source="Wikipedia contributors, 'Complement (set theory)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Complement_(complexity)#Complement_of_regular_languages", prerequisites=["nfa_to_dfa"]))
register_atom(Atom(atom_type="algorithm", name="dfa_product", content="The product construction combines two DFAs M1, M2 into a single DFA recognising L(M1) intersect L(M2). States are pairs (q1, q2). Transitions: delta((q1,q2), a) = (delta1(q1,a), delta2(q2,a)). Accept states: F1 x F2. For union: (F1 x Q2) union (Q1 x F2).", example="M1 accepts strings with even 0s, M2 accepts strings with even 1s. Product accepts strings with both even 0s and even 1s.", tier=5, domain="automata_theory", source="Wikipedia contributors, 'Product automaton', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Product_automaton", prerequisites=["nfa_to_dfa"]))
register_atom(Atom(atom_type="algorithm", name="regex_to_dfa_direct", content="Direct construction from regex to DFA: compute firstpos, lastpos, followpos for each node in the syntax tree, then build DFA states as subsets of positions. Avoids NFA intermediate. Positions represent leaves of the augmented regex (r)#.", example="Regex (a|b)*abb: augmented (a|b)*abb#. Positions: a=1, b=2, a=3, b=4, b=5, #=6. Start state = firstpos(root).", tier=6, domain="automata_theory", source="Aho, Sethi, Ullman, 'Compilers: Principles, Techniques, and Tools'.", source_url="https://en.wikipedia.org/wiki/Thompson%27s_construction", prerequisites=["regex_to_nfa"]))
register_atom(Atom(atom_type="concept", name="language_operations", content="Regular languages are closed under union (L1 | L2), concatenation (L1.L2), Kleene star (L*), complement, intersection, and difference. These correspond to automata constructions: NFA union, NFA concatenation, NFA star, DFA complement, product DFA, complement+intersection.", example="L1 = a*, L2 = b*. L1 union L2 = a* | b*. L1 intersect L2 = {epsilon}. L1 concat L2 = a*b*.", tier=5, domain="automata_theory", source="Wikipedia contributors, 'Regular language', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Regular_language#Closure_properties", prerequisites=["nfa_to_dfa"]))
register_atom(Atom(atom_type="algorithm", name="state_equivalence", content="Two DFA states p, q are equivalent if for every string w, delta(p,w) in F iff delta(q,w) in F. Hopcroft's algorithm partitions states into equivalence classes by iterative refinement. Initially: {F, Q-F}. Refine: split classes where inputs lead to different classes.", example="States {0,1,2}, F={2}. Initial: {0,1},{2}. Input a: 0->1, 1->2 (different classes) -> split {0},{1},{2}. 3 equivalence classes = 3-state minimal DFA.", tier=6, domain="automata_theory", source="Wikipedia contributors, 'DFA minimization', Wikipedia.", source_url="https://en.wikipedia.org/wiki/DFA_minimization", prerequisites=["dfa_complement"]))
register_atom(Atom(atom_type="concept", name="myhill_nerode", content="The Myhill-Nerode theorem states that a language L is regular iff the number of equivalence classes of the right-invariance relation ~L is finite. Two strings x, y are equivalent (x ~L y) iff for all z, xz in L iff yz in L. The number of classes equals the number of states in the minimal DFA.", example="L = {a^n b^n}: 'a', 'aa', 'aaa',... are all distinct under ~L (each needs different number of b's). Infinite classes -> L is not regular.", tier=6, domain="automata_theory", source="Wikipedia contributors, 'Myhill-Nerode theorem', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Myhill%E2%80%93Nerode_theorem", prerequisites=["state_equivalence"]))

# -- Numerical methods ext2 --
register_atom(Atom(atom_type="algorithm", name="gaussian_quadrature", content="Gaussian quadrature approximates integrals using optimally chosen nodes and weights: integral f(x)dx ~ sum w_i*f(x_i). For n points, it exactly integrates polynomials of degree 2n-1. Gauss-Legendre uses Legendre polynomial roots on [-1,1].", example="2-point Gauss-Legendre: nodes x = +/-1/sqrt(3), weights w = 1. integral_{-1}^{1} x^2 dx = 1*(1/3) + 1*(1/3) = 2/3. Exact.", tier=5, domain="numerical_methods", source="Wikipedia contributors, 'Gaussian quadrature', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Gaussian_quadrature", prerequisites=["simpson_rule"]))
register_atom(Atom(atom_type="algorithm", name="adams_bashforth", content="Adams-Bashforth methods are explicit multistep ODE solvers. The k-step method uses k previous values to predict the next: y_{n+1} = y_n + h*sum_{j=0}^{k-1} b_j*f_{n-j}. AB2: y_{n+1} = y_n + h*(3f_n - f_{n-1})/2.", example="y' = y, y_0=1, h=0.1. AB2 (after startup with Euler): y_1=1.1, f_0=1, f_1=1.1. y_2=1.1+0.05*(3*1.1-1)=1.1+0.115=1.215.", tier=6, domain="numerical_methods", source="Wikipedia contributors, 'Linear multistep method', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Linear_multistep_method", prerequisites=["euler_method_ode"]))
register_atom(Atom(atom_type="algorithm", name="newton_interpolation", content="Newton's divided difference interpolation constructs a polynomial through n+1 points: p(x) = f[x_0] + f[x_0,x_1](x-x_0) + f[x_0,x_1,x_2](x-x_0)(x-x_1) + ... Divided differences are computed recursively: f[x_i,...,x_j] = (f[x_{i+1},...,x_j] - f[x_i,...,x_{j-1}]) / (x_j - x_i).", example="Points (1,1), (2,4), (3,9). f[x_0]=1, f[x_0,x_1]=(4-1)/(2-1)=3, f[x_0,x_1,x_2]=(5-3)/(3-1)=1. p(x)=1+3(x-1)+1(x-1)(x-2)=x^2.", tier=5, domain="numerical_methods", source="Wikipedia contributors, 'Newton's method (interpolation)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Newton_polynomial", prerequisites=["interpolation_lagrange"]))
register_atom(Atom(atom_type="formula", name="numerical_integration_error", content="Error bounds for numerical integration: Trapezoidal rule error = -h^2(b-a)/12 * f''(xi). Simpson's rule error = -h^4(b-a)/180 * f^(4)(xi). Richardson extrapolation improves accuracy by combining estimates at different step sizes.", example="Trapezoidal, f(x)=x^2 on [0,1], h=0.5: error bound = -0.25*1/12*2 = -0.042. Actual error: |0.375-0.333| = 0.042.", tier=5, domain="numerical_methods", source="Wikipedia contributors, 'Numerical integration', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Numerical_integration#Error", prerequisites=["trapezoidal_rule"]))
register_atom(Atom(atom_type="algorithm", name="eigenvalue_power_iteration", content="Power iteration finds the dominant eigenvalue/eigenvector of a matrix. Starting from a random vector v, iterate v_{k+1} = A*v_k / ||A*v_k||. The Rayleigh quotient v^T*A*v / v^T*v converges to the largest eigenvalue. Convergence rate: |lambda_2/lambda_1|.", example="A = [[2,1],[1,2]]. v_0=[1,0]. v_1=A*v_0=[2,1]/sqrt(5). v_2=A*v_1=[5,4]/sqrt(41). Eigenvalue ~ v^T*A*v/v^T*v = 2.95 -> 3.", tier=5, domain="numerical_methods", source="Wikipedia contributors, 'Power iteration', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Power_iteration", prerequisites=["eigenvalue"]))
register_atom(Atom(atom_type="algorithm", name="nonlinear_system", content="Newton's method for nonlinear systems: x_{k+1} = x_k - J(x_k)^{-1} * F(x_k), where J is the Jacobian matrix. Converges quadratically near a solution. For 2D: solve [J]*[dx,dy]^T = -[F] at each iteration.", example="f1=x^2+y-1, f2=x+y^2-1. J=[[2x,1],[1,2y]]. At (0.5,0.5): F=[-.25,-.25], J=[[1,1],[1,1]]. Singular -> perturb or use damped Newton.", tier=6, domain="numerical_methods", source="Wikipedia contributors, 'Newton's method (systems)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Newton%27s_method#Systems_of_equations", prerequisites=["newton_raphson"]))
