"""Knowledge atoms for sequences, geology, measurement, linguistics, info theory, networking, nuclear, and fluid ext."""
from engram_generator.base import Atom
from engram_generator.atoms.registry import register_atom

# -- Sequences ext --
register_atom(Atom(atom_type="formula", name="harmonic_series", content="The harmonic series sum_{n=1}^N 1/n diverges but grows as ln(N) + gamma, where gamma = 0.5772 is the Euler-Mascheroni constant. The partial sum H_N = sum_{k=1}^N 1/k.", example="H_4 = 1 + 1/2 + 1/3 + 1/4 = 2.0833.", tier=5, domain="sequences", source="Wikipedia contributors, 'Harmonic series', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Harmonic_series_(mathematics)", prerequisites=["summation"]))
register_atom(Atom(atom_type="formula", name="telescoping_series", content="A telescoping series has terms that cancel in pairs: sum_{k=1}^n (a_k - a_{k+1}) = a_1 - a_{n+1}. Common form: 1/(k(k+1)) = 1/k - 1/(k+1).", example="sum_{k=1}^3 1/(k(k+1)) = (1-1/2)+(1/2-1/3)+(1/3-1/4) = 1-1/4 = 3/4.", tier=5, domain="sequences", source="Wikipedia contributors, 'Telescoping series', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Telescoping_series", prerequisites=["partial_fractions"]))
register_atom(Atom(atom_type="formula", name="recurrence_second_order", content="A second-order linear recurrence a_n = p*a_{n-1} + q*a_{n-2} has characteristic equation r^2 - p*r - q = 0. If roots r1 != r2: a_n = A*r1^n + B*r2^n. If r1 = r2 = r: a_n = (A + Bn)*r^n.", example="Fibonacci: a_n = a_{n-1} + a_{n-2}. Roots: (1+sqrt(5))/2, (1-sqrt(5))/2. a_n = (phi^n - psi^n)/sqrt(5).", tier=5, domain="sequences", source="Wikipedia contributors, 'Recurrence relation', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Recurrence_relation", prerequisites=["quadratic"]))
register_atom(Atom(atom_type="formula", name="power_series_eval", content="A power series sum_{n=0}^inf a_n * x^n converges within its radius of convergence R = 1/limsup|a_n|^{1/n}. Evaluation at x: partial sum S_N = sum_{n=0}^N a_n*x^n.", example="e^x = sum x^n/n!. At x=1, N=4: S_4 = 1+1+0.5+0.167+0.042 = 2.708 (vs e=2.718).", tier=5, domain="sequences", source="Wikipedia contributors, 'Power series', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Power_series", prerequisites=["geometric_sequence"]))
register_atom(Atom(atom_type="formula", name="sequence_limit", content="The limit of a sequence {a_n} is L if for every epsilon > 0 there exists N such that |a_n - L| < epsilon for all n > N. Common limits: (1+1/n)^n -> e, n^{1/n} -> 1, a^n/n! -> 0 for any a.", example="a_n = (2n+1)/(3n-1). Divide by n: (2+1/n)/(3-1/n) -> 2/3.", tier=5, domain="sequences", source="Wikipedia contributors, 'Limit of a sequence', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Limit_of_a_sequence", prerequisites=["limit"]))
register_atom(Atom(atom_type="concept", name="fibonacci_properties", content="The Fibonacci sequence F_n = F_{n-1} + F_{n-2} satisfies: Cassini's identity F_{n-1}*F_{n+1} - F_n^2 = (-1)^n; the addition formula F_{m+n} = F_m*F_{n+1} + F_{m-1}*F_n; and gcd(F_m, F_n) = F_{gcd(m,n)}.", example="F_5=5, F_4=3, F_6=8. Cassini: 3*8 - 25 = 24-25 = -1 = (-1)^5. Verified.", tier=5, domain="sequences", source="Wikipedia contributors, 'Fibonacci sequence', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Fibonacci_sequence", prerequisites=["fibonacci"]))

# -- Geology ext --
register_atom(Atom(atom_type="concept", name="mineral_identification", content="Minerals are identified by physical properties: hardness (Mohs scale 1-10), lustre (metallic, vitreous, etc.), streak colour, cleavage/fracture, crystal system, and specific gravity. Definitive identification uses X-ray diffraction or chemical analysis.", example="Quartz: hardness 7, vitreous lustre, white streak, conchoidal fracture, hexagonal system, SG=2.65.", tier=5, domain="geology", source="Wikipedia contributors, 'Mineral', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Mineral#Physical_properties", prerequisites=[]))
register_atom(Atom(atom_type="concept", name="rock_cycle", content="The rock cycle describes transformations between three rock types: igneous (from magma crystallisation), sedimentary (from deposition and lithification), and metamorphic (from heat/pressure). Each can transform into any other through weathering, melting, metamorphism, or lithification.", example="Granite (igneous) -> weathering -> sandstone (sedimentary) -> heat/pressure -> quartzite (metamorphic) -> melting -> magma -> granite.", tier=5, domain="geology", source="Wikipedia contributors, 'Rock cycle', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Rock_cycle", prerequisites=[]))
register_atom(Atom(atom_type="concept", name="stratigraphy", content="Stratigraphy studies rock layers (strata) and their chronological ordering. Key principles: superposition (younger on top), original horizontality, lateral continuity, cross-cutting relationships, and faunal succession. Index fossils date strata relatively.", example="Layer A (trilobites) below Layer B (ammonites): A is Cambrian (~500 Ma), B is Jurassic (~150 Ma). Unconformity between them = missing time.", tier=5, domain="geology", source="Wikipedia contributors, 'Stratigraphy', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Stratigraphy", prerequisites=[]))
register_atom(Atom(atom_type="formula", name="earthquake_energy", content="The energy released by an earthquake relates to magnitude M by: log10(E) = 1.5*M + 4.8 (in joules). Each unit increase in magnitude represents ~31.6x more energy. The Richter scale is logarithmic: a M7 is 1000x more energetic than M5.", example="M=6: log10(E) = 1.5*6+4.8 = 13.8. E = 10^13.8 = 6.31e13 J. M=7: E = 10^15.3 = 2.0e15 J. Ratio: ~31.6x.", tier=5, domain="geology", source="Wikipedia contributors, 'Richter magnitude scale', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Richter_magnitude_scale", prerequisites=["logarithm"]))
register_atom(Atom(atom_type="concept", name="geologic_time", content="The geologic time scale divides Earth's 4.54 billion year history into eons (Hadean, Archean, Proterozoic, Phanerozoic), eras (Paleozoic, Mesozoic, Cenozoic), periods (Cambrian through Quaternary), and epochs. Absolute ages come from radiometric dating.", example="Cretaceous-Paleogene boundary: 66 Ma. End of dinosaurs. Cambrian explosion: ~541 Ma. First complex life.", tier=5, domain="geology", source="Wikipedia contributors, 'Geologic time scale', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Geologic_time_scale", prerequisites=[]))
register_atom(Atom(atom_type="formula", name="porosity_permeability", content="Porosity phi = V_void/V_total is the fraction of void space. Permeability k (Darcy) measures fluid flow capacity: Q = k*A*dP/(mu*L) (Darcy's law). High porosity does not guarantee high permeability (clay: high porosity, low permeability).", example="phi=0.25, k=100 mD, A=1 m^2, dP=100 kPa, mu=0.001 Pa-s, L=1 m: Q = 100e-15*1*100e3/(0.001*1) = 0.01 m^3/s.", tier=5, domain="geology", source="Wikipedia contributors, 'Porosity', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Porosity", prerequisites=["division"]))

# -- Measurement ext --
register_atom(Atom(atom_type="formula", name="error_propagation", content="For f(x, y, ...) with independent uncertainties: sigma_f = sqrt((df/dx)^2*sigma_x^2 + (df/dy)^2*sigma_y^2 + ...). For addition: sigma_{a+b} = sqrt(sigma_a^2 + sigma_b^2). For multiplication: sigma_{ab}/|ab| = sqrt((sigma_a/a)^2 + (sigma_b/b)^2).", example="f = x*y, x=5.0+/-0.1, y=3.0+/-0.2: sigma_f/15 = sqrt((0.1/5)^2 + (0.2/3)^2) = sqrt(0.0004+0.0044) = 0.0693. sigma_f = 1.04.", tier=5, domain="measurement", source="Wikipedia contributors, 'Propagation of uncertainty', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Propagation_of_uncertainty", prerequisites=["partial_derivative"]))
register_atom(Atom(atom_type="formula", name="dimensional_analysis_compute", content="Dimensional analysis checks equation consistency by verifying units balance. Every physical equation must be dimensionally homogeneous. Also used to derive relations: if F depends on m, a, then [F] = [m][a] = kg*m/s^2.", example="v = sqrt(2*g*h). [v] = m/s. [sqrt(g*h)] = sqrt(m/s^2 * m) = sqrt(m^2/s^2) = m/s. Consistent.", tier=4, domain="measurement", source="Wikipedia contributors, 'Dimensional analysis', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Dimensional_analysis", prerequisites=[]))
register_atom(Atom(atom_type="algorithm", name="significant_figures_calc", content="Significant figures indicate measurement precision. Rules: non-zero digits are significant, zeros between non-zeroes are significant, trailing zeros after decimal are significant. For multiplication/division: result has fewest sig figs of inputs. For addition/subtraction: result has fewest decimal places.", example="3.14 * 2.1 = 6.594 -> 6.6 (2 sig figs). 3.14 + 2.1 = 5.24 -> 5.2 (1 decimal place).", tier=4, domain="measurement", source="Wikipedia contributors, 'Significant figures', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Significant_figures", prerequisites=["rounding"]))
register_atom(Atom(atom_type="formula", name="calibration_curve", content="A calibration curve relates instrument response to known standard concentrations via linear regression: y = mx + b. The concentration of an unknown is found by inverting: x_unknown = (y_measured - b) / m. R^2 should be > 0.99.", example="Standards: (1, 0.15), (2, 0.32), (3, 0.47), (4, 0.63). Regression: y = 0.16x - 0.01. Unknown y = 0.40: x = (0.40+0.01)/0.16 = 2.56.", tier=5, domain="measurement", source="Wikipedia contributors, 'Calibration curve', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Calibration_curve", prerequisites=["linear_regression"]))
register_atom(Atom(atom_type="concept", name="accuracy_precision", content="Accuracy is closeness to the true value; precision is repeatability. A measurement can be precise but inaccurate (systematic error) or accurate but imprecise (random error). Accuracy is assessed against standards; precision by standard deviation of repeated measurements.", example="True value: 10.0. Measurements: [10.1, 10.2, 10.0, 10.1] = accurate and precise. [9.5, 9.6, 9.5, 9.5] = precise but inaccurate (bias of -0.5).", tier=4, domain="measurement", source="Wikipedia contributors, 'Accuracy and precision', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Accuracy_and_precision", prerequisites=[]))
register_atom(Atom(atom_type="formula", name="logarithmic_scales", content="Logarithmic scales compress wide-ranging data. Common examples: decibels (dB = 10*log10(P/P_ref)), pH (-log10[H+]), Richter magnitude, stellar magnitude. A factor of 10 in the quantity equals 1 unit on the log scale.", example="Sound power ratio 1000:1. dB = 10*log10(1000) = 30 dB. pH of [H+]=1e-4 M: pH = -log10(1e-4) = 4.", tier=5, domain="measurement", source="Wikipedia contributors, 'Logarithmic scale', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Logarithmic_scale", prerequisites=["logarithm"]))

# -- Linguistics ext --
register_atom(Atom(atom_type="algorithm", name="syllable_count", content="English syllable counting heuristic: count vowel groups (a, e, i, o, u, y), subtract silent-e endings, add back '-le' endings if preceded by a consonant. Minimum 1 syllable per word.", example="'simple': vowel groups [i, e] = 2. Silent-e: -1. '-le': +1. Total = 2. 'create': [ea, e] = 2. Silent-e: -1. Total = 2 (cre-ate).", tier=4, domain="linguistics", source="Wikipedia contributors, 'Syllable', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Syllable", prerequisites=[]))
register_atom(Atom(atom_type="concept", name="ipa_transcription", content="The International Phonetic Alphabet (IPA) provides a symbol for each speech sound. English consonants include plosives (/p b t d k g/), fricatives (/f v s z/), nasals (/m n/), and approximants (/l r w j/). Vowels are mapped by height and backness.", example="'cat' = /kaet/. 'think' = /theta-i-ng-k/. 'shoe' = /sh-u:/. Stress marked with apostrophe: 'banana' = /b@-'nae-n@/.", tier=5, domain="linguistics", source="Wikipedia contributors, 'International Phonetic Alphabet', Wikipedia.", source_url="https://en.wikipedia.org/wiki/International_Phonetic_Alphabet", prerequisites=[]))
register_atom(Atom(atom_type="concept", name="morphological_analysis", content="Morphological analysis decomposes words into morphemes: free (can stand alone) and bound (prefixes, suffixes, infixes). Inflectional morphemes change grammatical function (dog-s, walk-ed). Derivational morphemes change meaning or part of speech (un-happy, teach-er).", example="'unhappiness': un- (prefix, bound) + happy (free) + -ness (suffix, bound) = 3 morphemes. un- is derivational, -ness is derivational.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Morphology (linguistics)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Morphology_(linguistics)", prerequisites=[]))
register_atom(Atom(atom_type="formula", name="word_frequency", content="Word frequency follows Zipf's law: the frequency of the r-th most common word is f(r) = C / r^alpha, where alpha ~ 1 and C is a normalisation constant. In English, 'the' is #1 (~7%), 'of' is #2 (~3.5%), 'and' is #3 (~2.8%).", example="Corpus of 1000 words. 'the' appears 70 times (rank 1). 'of' appears 35 times (rank 2). 70/35 = 2 ~ 2/1. Zipf confirmed.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Zipf's law', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Zipf%27s_law", prerequisites=["logarithm"]))
register_atom(Atom(atom_type="formula", name="language_entropy", content="The entropy of a language measures its information content per symbol: H = -sum p(x)*log2(p(x)). English has H ~ 1.0-1.5 bits/character (accounting for redundancy). Maximum entropy (uniform) for 26 letters = log2(26) = 4.7 bits.", example="Alphabet {a, b} with P(a)=0.9, P(b)=0.1: H = -0.9*log2(0.9) - 0.1*log2(0.1) = 0.469 bits.", tier=5, domain="linguistics", source="Wikipedia contributors, 'Entropy (information theory)', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Entropy_(information_theory)", prerequisites=["info_entropy"]))
register_atom(Atom(atom_type="formula", name="edit_distance_linguistic", content="The Levenshtein distance between two strings is the minimum number of single-character edits (insertions, deletions, substitutions) to transform one into the other. Computed via dynamic programming: d[i,j] = min(d[i-1,j]+1, d[i,j-1]+1, d[i-1,j-1] + (s[i]!=t[j])).", example="'kitten' -> 'sitting': k->s (sub), e->i (sub), +g (insert) = 3 edits.", tier=4, domain="linguistics", source="Wikipedia contributors, 'Levenshtein distance', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Levenshtein_distance", prerequisites=["edit_distance"]))

# -- Information theory ext --
register_atom(Atom(atom_type="formula", name="conditional_entropy", content="The conditional entropy H(Y|X) measures the remaining uncertainty in Y given X: H(Y|X) = -sum_{x,y} p(x,y)*log2(p(y|x)). Chain rule: H(X,Y) = H(X) + H(Y|X). H(Y|X) <= H(Y) with equality iff X and Y are independent.", example="Joint: p(0,0)=0.5, p(0,1)=0, p(1,0)=0.25, p(1,1)=0.25. H(Y|X) = -0.5*log2(1) - 0.25*log2(0.5) - 0.25*log2(0.5) = 0.5 bits.", tier=5, domain="information_theory", source="Wikipedia contributors, 'Conditional entropy', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Conditional_entropy", prerequisites=["info_entropy"]))
register_atom(Atom(atom_type="law", name="data_processing_inequality", content="The data processing inequality states that no processing of data can increase the information that Y contains about X: if X -> Y -> Z forms a Markov chain, then I(X;Z) <= I(X;Y). Information can only be lost, never created, by local operations.", example="X = fair coin, Y = X XOR noise(0.1), Z = quantize(Y). I(X;Y) = 0.531 bits. I(X;Z) <= 0.531 bits.", tier=6, domain="information_theory", source="Wikipedia contributors, 'Data processing inequality', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Data_processing_inequality", prerequisites=["mutual_information"]))
register_atom(Atom(atom_type="formula", name="rate_distortion", content="Rate-distortion theory gives the minimum rate R(D) to represent a source with average distortion at most D: R(D) = min_{p(x_hat|x): E[d(x,x_hat)]<=D} I(X; X_hat). For a Gaussian source with MSE distortion: R(D) = 0.5*log2(sigma^2/D) for D <= sigma^2.", example="Gaussian source sigma^2=1, D=0.25: R(0.25) = 0.5*log2(1/0.25) = 0.5*2 = 1 bit/sample.", tier=6, domain="information_theory", source="Wikipedia contributors, 'Rate-distortion theory', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Rate%E2%80%93distortion_theory", prerequisites=["info_entropy"]))
register_atom(Atom(atom_type="concept", name="typical_set", content="The typical set A_epsilon^n contains sequences x^n whose empirical entropy is close to H(X): |(-1/n)*log2(p(x^n)) - H(X)| < epsilon. By the AEP, P(x^n in A) > 1-epsilon for large n, and |A| ~ 2^{nH(X)}.", example="Binary source, P(0)=0.9. H=0.469. n=100: |A| ~ 2^{46.9} ~ 10^14 typical sequences out of 2^100 ~ 10^30 total.", tier=6, domain="information_theory", source="Wikipedia contributors, 'Typical set', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Typical_set", prerequisites=["info_entropy"]))
register_atom(Atom(atom_type="law", name="kraft_mcmillan", content="The Kraft-McMillan inequality states that a uniquely decodable code with codeword lengths l_1, ..., l_n over alphabet of size r exists iff sum r^{-l_i} <= 1. For binary (r=2): sum 2^{-l_i} <= 1. Equality means the code is complete (no unused prefix space).", example="Lengths {1, 2, 3, 3}: 2^{-1}+2^{-2}+2^{-3}+2^{-3} = 0.5+0.25+0.125+0.125 = 1. Complete prefix code.", tier=5, domain="information_theory", source="Wikipedia contributors, 'Kraft's inequality', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Kraft%27s_inequality", prerequisites=["huffman_coding"]))
register_atom(Atom(atom_type="formula", name="joint_entropy", content="The joint entropy H(X, Y) = -sum_{x,y} p(x,y)*log2(p(x,y)) measures total uncertainty of the pair. H(X,Y) <= H(X) + H(Y) with equality iff independent. Chain rule: H(X,Y) = H(X) + H(Y|X).", example="Independent X, Y each uniform on {0,1}: H(X,Y) = H(X)+H(Y) = 1+1 = 2 bits.", tier=5, domain="information_theory", source="Wikipedia contributors, 'Joint entropy', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Joint_entropy", prerequisites=["info_entropy"]))

# -- Networking ext --
register_atom(Atom(atom_type="algorithm", name="ip_subnetting", content="IP subnetting divides a network using a subnet mask. A /24 network has 256 addresses (254 usable). Network address = IP AND mask. Broadcast = network OR (NOT mask). Host bits = 32 - prefix length. Number of hosts = 2^host_bits - 2.", example="192.168.1.0/26: mask=255.255.255.192. Hosts=2^6-2=62. Network=192.168.1.0, broadcast=192.168.1.63, range=.1-.62.", tier=4, domain="networking", source="Wikipedia contributors, 'Subnetwork', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Subnetwork", prerequisites=["binary_arithmetic"]))
register_atom(Atom(atom_type="concept", name="arp_resolution", content="ARP (Address Resolution Protocol) maps IP addresses to MAC addresses on a local network. A host broadcasts 'who has IP x.x.x.x?' The owner replies with its MAC. Results are cached in an ARP table with timeout.", example="Host A (192.168.1.10) wants to reach 192.168.1.20. Broadcasts ARP request. Host B replies: 192.168.1.20 is at AA:BB:CC:DD:EE:FF.", tier=4, domain="networking", source="Wikipedia contributors, 'Address Resolution Protocol', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Address_Resolution_Protocol", prerequisites=[]))
register_atom(Atom(atom_type="concept", name="dns_resolution", content="DNS resolves domain names to IP addresses through a hierarchical system: root servers -> TLD servers (.com, .org) -> authoritative servers. Recursive resolution queries each level. Results are cached with TTL (time-to-live).", example="Query www.example.com: root -> .com TLD -> example.com authoritative -> returns 93.184.216.34. Cached for TTL=3600s.", tier=4, domain="networking", source="Wikipedia contributors, 'Domain Name System', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Domain_Name_System", prerequisites=[]))
register_atom(Atom(atom_type="algorithm", name="tcp_congestion", content="TCP congestion control uses AIMD (additive increase, multiplicative decrease). Slow start: cwnd doubles each RTT until ssthresh. Congestion avoidance: cwnd += 1 MSS per RTT. On loss: ssthresh = cwnd/2, cwnd = 1 (Tahoe) or cwnd/2 (Reno).", example="MSS=1KB, ssthresh=8. Slow start: cwnd=1,2,4,8. Congestion avoidance: 9,10,11... Loss at 12: ssthresh=6, cwnd=1 (Tahoe) or cwnd=6 (Reno).", tier=5, domain="networking", source="Wikipedia contributors, 'TCP congestion control', Wikipedia.", source_url="https://en.wikipedia.org/wiki/TCP_congestion_control", prerequisites=["tcp_window"]))
register_atom(Atom(atom_type="algorithm", name="checksum_compute", content="A checksum detects errors by summing data words and appending the complement. Internet checksum: sum 16-bit words with carry wraparound, take one's complement. Receiver sums all words including checksum; result should be 0xFFFF.", example="Words: 0x4500, 0x003C, 0x1C46. Sum=0x6382. One's complement=0x9C7D. Receiver: sum all including 0x9C7D = 0xFFFF.", tier=4, domain="networking", source="Wikipedia contributors, 'IPv4 header checksum', Wikipedia.", source_url="https://en.wikipedia.org/wiki/IPv4_header_checksum", prerequisites=["binary_arithmetic"]))
register_atom(Atom(atom_type="concept", name="sliding_window", content="Sliding window protocols allow multiple frames in flight for efficient link utilisation. Window size W determines max unacknowledged frames. Go-Back-N retransmits all from the error; Selective Repeat retransmits only the lost frame. Utilisation: U = W/(1+2a) where a = propagation/transmission delay ratio.", example="W=4, a=2: U = 4/(1+4) = 0.8 (80% utilisation). If W=1 (stop-and-wait): U = 1/5 = 0.2.", tier=5, domain="networking", source="Wikipedia contributors, 'Sliding window protocol', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Sliding_window_protocol", prerequisites=["tcp_window"]))

# -- Nuclear ext --
register_atom(Atom(atom_type="formula", name="activity", content="Radioactivity is measured in Becquerels (1 Bq = 1 decay/s). Activity A = lambda*N = (ln2/t_half)*N, where N is the number of radioactive atoms. Activity decreases exponentially: A(t) = A_0*exp(-lambda*t).", example="N=1e12 atoms, t_half=5730 yr: lambda=ln2/5730=1.21e-4/yr. A=1.21e-4*1e12=1.21e8 decays/yr.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Radioactive decay', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Radioactive_decay#Rates", prerequisites=["radioactive_decay"]))
register_atom(Atom(atom_type="formula", name="carbon_dating", content="Carbon-14 dating uses the decay of C-14 (t_half=5730 yr) to estimate age: t = -t_half/ln(2) * ln(A/A_0), where A is current activity and A_0 is initial activity (assumed constant at ~15 dpm/g carbon).", example="Sample: A=3.75 dpm/g, A_0=15 dpm/g. t = -5730/ln2 * ln(3.75/15) = 8267 * ln(4) = 8267*1.386 = 11,460 years.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Radiocarbon dating', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Radiocarbon_dating", prerequisites=["radioactive_decay"]))
register_atom(Atom(atom_type="concept", name="nuclear_fission", content="Nuclear fission splits a heavy nucleus into lighter fragments, releasing energy. The energy comes from the binding energy difference: E ~ 200 MeV per U-235 fission. Critical mass is the minimum mass for a sustained chain reaction. Moderated neutrons are more likely to cause fission.", example="U-235 + n -> Ba-141 + Kr-92 + 3n. Mass defect: 0.215 amu. E = 0.215*931.5 = 200 MeV.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Nuclear fission', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Nuclear_fission", prerequisites=["mass_defect"]))
register_atom(Atom(atom_type="concept", name="nuclear_fusion", content="Nuclear fusion combines light nuclei to form heavier ones, releasing energy. The proton-proton chain powers the Sun: 4H -> He-4 + 2e+ + 2nu_e + 26.7 MeV. Requires temperatures > 10^7 K to overcome Coulomb repulsion. The Lawson criterion gives minimum n*T*tau for energy breakeven.", example="D + T -> He-4 + n + 17.6 MeV. Breakeven: n*tau > 10^20 m^-3*s at T = 10 keV.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Nuclear fusion', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Nuclear_fusion", prerequisites=["mass_defect"]))
register_atom(Atom(atom_type="formula", name="dose_calculation", content="Radiation dose: absorbed dose D = E_absorbed/mass (Gray, 1 Gy = 1 J/kg). Equivalent dose H = D*w_R (Sievert), where w_R is the radiation weighting factor (1 for gamma/beta, 20 for alpha). Effective dose accounts for organ sensitivity.", example="1 Gy of alpha radiation: H = 1*20 = 20 Sv. 1 Gy of gamma: H = 1*1 = 1 Sv. Annual limit: 1 mSv public, 20 mSv occupational.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Absorbed dose', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Absorbed_dose", prerequisites=["division"]))
register_atom(Atom(atom_type="concept", name="neutron_moderation", content="Neutron moderation slows fast neutrons (~2 MeV) to thermal energies (~0.025 eV) to increase fission probability. Moderators: light water (H2O), heavy water (D2O), graphite. Energy loss per collision: xi = 1 + (A-1)^2/(2A) * ln((A-1)/(A+1)). Number of collisions to thermalise: n = ln(E_fast/E_thermal) / xi.", example="H2O moderator (A=1): xi=1. n = ln(2e6/0.025)/1 = 18.2, so ~18 collisions. Graphite (A=12): xi=0.158, n=115 collisions.", tier=5, domain="nuclear_physics", source="Wikipedia contributors, 'Neutron moderator', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Neutron_moderator", prerequisites=["logarithm"]))

# -- Fluid mechanics ext --
register_atom(Atom(atom_type="formula", name="pipe_flow", content="For laminar pipe flow (Re < 2300), the Hagen-Poiseuille equation gives flow rate: Q = pi*d^4*dP/(128*mu*L), where d is diameter, dP is pressure drop, mu is viscosity, L is length. Friction factor f = 64/Re.", example="d=0.02m, L=10m, dP=50kPa, mu=0.001 Pa-s: Q=pi*0.02^4*50e3/(128*0.001*10) = 3.93e-4 m^3/s.", tier=5, domain="fluid_mechanics", source="Wikipedia contributors, 'Hagen-Poiseuille equation', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Hagen%E2%80%93Poiseuille_equation", prerequisites=["reynolds_number"]))
register_atom(Atom(atom_type="formula", name="venturi_meter", content="A Venturi meter measures flow rate using Bernoulli's equation: Q = A_2*sqrt(2*dP/(rho*(1-(A_2/A_1)^2))), where A_1, A_2 are the pipe and throat areas, dP is the pressure difference.", example="A_1=0.01 m^2, A_2=0.005 m^2, dP=20 kPa, rho=1000: Q=0.005*sqrt(2*20e3/(1000*(1-0.25)))=0.005*sqrt(53.3)=0.0365 m^3/s.", tier=5, domain="fluid_mechanics", source="Wikipedia contributors, 'Venturi effect', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Venturi_effect", prerequisites=["bernoulli"]))
register_atom(Atom(atom_type="formula", name="stokes_drag", content="For a sphere at low Reynolds number (Re << 1), Stokes' law gives drag force: F_d = 6*pi*mu*r*v, where mu is dynamic viscosity, r is radius, v is velocity. Terminal velocity: v_t = 2*r^2*(rho_p-rho_f)*g/(9*mu).", example="Sphere r=1mm in water (mu=0.001, rho_f=1000), rho_p=2500: v_t=2*1e-6*1500*9.81/(9*0.001)=3.27 mm/s.", tier=5, domain="fluid_mechanics", source="Wikipedia contributors, 'Stokes' law', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Stokes%27_law", prerequisites=["drag_force"]))
register_atom(Atom(atom_type="formula", name="hydraulic_jump", content="A hydraulic jump occurs when supercritical flow (Fr > 1) transitions to subcritical flow (Fr < 1). The conjugate depth ratio: y2/y1 = 0.5*(-1 + sqrt(1 + 8*Fr_1^2)), where Fr_1 = v_1/sqrt(g*y_1). Energy is dissipated in the jump.", example="y1=0.1m, v1=5m/s: Fr1=5/sqrt(9.81*0.1)=5.05. y2/y1=0.5*(-1+sqrt(1+8*25.5))=0.5*(-1+14.4)=6.7. y2=0.67m.", tier=5, domain="fluid_mechanics", source="Wikipedia contributors, 'Hydraulic jump', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Hydraulic_jump", prerequisites=["reynolds_number"]))
register_atom(Atom(atom_type="formula", name="open_channel", content="Manning's equation for open channel flow: v = (1/n)*R_h^(2/3)*S^(1/2), where n is Manning's roughness coefficient, R_h is hydraulic radius (A/P), S is the bed slope. Q = v*A.", example="Rectangular channel: width=2m, depth=0.5m, n=0.015, S=0.001. A=1, P=3, R_h=0.333. v=(1/0.015)*0.333^0.667*0.001^0.5=0.67 m/s.", tier=5, domain="fluid_mechanics", source="Wikipedia contributors, 'Manning formula', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Manning_formula", prerequisites=["reynolds_number"]))
register_atom(Atom(atom_type="formula", name="pump_power", content="Pump power P = rho*g*Q*H/eta, where Q is flow rate, H is total head, eta is pump efficiency. Total head H = (P2-P1)/(rho*g) + (v2^2-v1^2)/(2g) + (z2-z1) + h_f (friction losses).", example="Q=0.01 m^3/s, H=20m, rho=1000, eta=0.75: P=1000*9.81*0.01*20/0.75=2616 W=2.6 kW.", tier=5, domain="fluid_mechanics", source="Wikipedia contributors, 'Pump', Wikipedia.", source_url="https://en.wikipedia.org/wiki/Pump#Pump_power", prerequisites=["bernoulli"]))
