#!/usr/bin/env python3
"""Generate a comprehensive Markdown index of all generators.

Produces GENERATOR_INDEX.md with full bookkeeping for every generator:
task name, tier, domain, atom (formula, source, example), verification
method, library, handler status, prerequisites, and difficulty range.

Usage:
    python scripts/generate_index.py
    python scripts/generate_index.py --output docs/index.md
"""
import argparse
import os
import sys
from collections import defaultdict

from engram_generator.curriculum.registry import get_all_generators
from engram_generator.validation.registry import VERIFICATION_REGISTRY
from engram_generator.validation.library_verifier import LibraryVerifier
from engram_generator.validation.example_verifier import ExampleVerifier


def build_index() -> str:
    """Build the full Markdown index.

    Returns:
        Markdown string with the complete generator reference.
    """
    gens = sorted(get_all_generators(), key=lambda g: (g.tier, g.task_name))
    verifier = LibraryVerifier()
    handler_tasks = set(verifier.supported_tasks())
    example_verifier = ExampleVerifier()
    example_tasks = set(example_verifier.supported_tasks())

    by_tier = defaultdict(list)
    for g in gens:
        by_tier[g.tier].append(g)

    stats = _compute_stats(gens, handler_tasks)
    lines = []
    lines.append("# Engram Generator Index\n")
    stats["example_verified"] = len(example_tasks)
    lines.append(_summary_section(stats, len(gens)))
    lines.append(_stats_table(stats))

    for tier in sorted(by_tier.keys()):
        lines.append(_tier_section(tier, by_tier[tier], handler_tasks, example_tasks))

    return "\n".join(lines)


def _compute_stats(gens, handler_tasks):
    """Compute aggregate statistics.

    Args:
        gens: All generators.
        handler_tasks: Set of task names with library handlers.

    Returns:
        Dict with counts by category.
    """
    stats = {
        "total": len(gens),
        "library": 0,
        "library_with_handler": 0,
        "formula": 0,
        "reference": 0,
        "classification": 0,
        "with_atom": 0,
        "with_example": 0,
        "with_source_url": 0,
        "by_tier": defaultdict(int),
    }
    for g in gens:
        stats["by_tier"][g.tier] += 1
        entry = VERIFICATION_REGISTRY.get(g.task_name)
        if entry:
            stats[entry.method] = stats.get(entry.method, 0) + 1
            if entry.method == "library" and g.task_name in handler_tasks:
                stats["library_with_handler"] += 1
        atom = g.atom
        if atom is not None:
            stats["with_atom"] += 1
            if atom.example:
                stats["with_example"] += 1
            if atom.source_url:
                stats["with_source_url"] += 1
    return stats


def _summary_section(stats, total):
    """Build the summary section.

    Args:
        stats: Aggregate statistics dict.
        total: Total generator count.

    Returns:
        Markdown string.
    """
    return f"""
Auto-generated reference for all {total} generators in the Engram
Generator curriculum. Each entry documents the task, its verification
status, knowledge atom, and dependencies.

**Generated by** `scripts/generate_index.py`

---

## Summary

| Metric | Count | Coverage |
|--------|-------|----------|
| Total generators | {total} | |
| Library-verified (independent) | {stats['library_with_handler']} | {stats['library_with_handler']*100//total}% |
| Formula-verified (circular) | {stats['formula']} | {stats['formula']*100//total}% |
| Reference-verified | {stats['reference']} | {stats['reference']*100//total}% |
| Classification (no verifier) | {stats['classification']} | {stats['classification']*100//total}% |
| With knowledge atom | {stats['with_atom']} | {stats['with_atom']*100//total}% |
| With worked example | {stats['with_example']} | {stats['with_example']*100//total}% |
| With source URL | {stats['with_source_url']} | {stats['with_source_url']*100//total}% |
| Double-blind verified (textbook) | {stats.get('example_verified', 0)} | |

"""


def _stats_table(stats):
    """Build per-tier stats table.

    Args:
        stats: Aggregate statistics dict.

    Returns:
        Markdown table string.
    """
    lines = ["## Per-Tier Breakdown\n"]
    lines.append("| Tier | Generators | Library | Formula | Reference | Classification |")
    lines.append("|------|-----------|---------|---------|-----------|----------------|")

    gens = get_all_generators()
    by_tier = defaultdict(list)
    for g in gens:
        by_tier[g.tier].append(g)

    for tier in sorted(by_tier.keys()):
        tier_gens = by_tier[tier]
        total = len(tier_gens)
        lib = sum(1 for g in tier_gens if g.task_name in VERIFICATION_REGISTRY
                  and VERIFICATION_REGISTRY[g.task_name].method == "library")
        form = sum(1 for g in tier_gens if g.task_name in VERIFICATION_REGISTRY
                   and VERIFICATION_REGISTRY[g.task_name].method == "formula")
        ref = sum(1 for g in tier_gens if g.task_name in VERIFICATION_REGISTRY
                  and VERIFICATION_REGISTRY[g.task_name].method == "reference")
        clas = sum(1 for g in tier_gens if g.task_name in VERIFICATION_REGISTRY
                   and VERIFICATION_REGISTRY[g.task_name].method == "classification")
        lines.append(f"| {tier} | {total} | {lib} | {form} | {ref} | {clas} |")

    lines.append("")
    return "\n".join(lines)


def _tier_section(tier, gens, handler_tasks, example_tasks):
    """Build a section for one tier.

    Args:
        tier: Tier number.
        gens: Generators in this tier.
        handler_tasks: Set of task names with handlers.
        example_tasks: Set of task names with textbook example verification.

    Returns:
        Markdown string for the tier.
    """
    lines = [f"\n---\n\n## Tier {tier}\n"]

    by_module = defaultdict(list)
    for g in gens:
        mod = type(g).__module__.split(".")[-1]
        by_module[mod].append(g)

    for mod in sorted(by_module.keys()):
        lines.append(f"\n### {mod}\n")
        for g in sorted(by_module[mod], key=lambda x: x.task_name):
            lines.append(_generator_entry(g, handler_tasks, example_tasks))

    return "\n".join(lines)


def _generator_entry(g, handler_tasks, example_tasks):
    """Build a single generator entry.

    Args:
        g: Generator instance.
        handler_tasks: Set of task names with handlers.
        example_tasks: Set of task names with textbook example verification.

    Returns:
        Markdown string for the generator.
    """
    entry = VERIFICATION_REGISTRY.get(g.task_name)
    atom = g.atom

    lines = [f"#### `{g.task_name}`\n"]

    # Metadata table
    lines.append(f"| Field | Value |")
    lines.append(f"|-------|-------|")
    lines.append(f"| Class | `{type(g).__name__}` |")
    lines.append(f"| Module | `{type(g).__module__}` |")
    lines.append(f"| Tier | {g.tier} |")
    lines.append(f"| Difficulty | {g.min_difficulty}-{g.max_difficulty} |")
    lines.append(f"| Prerequisites | {', '.join(g.prerequisites) if g.prerequisites else 'none'} |")

    # Verification
    if entry:
        method = entry.method
        if method == "library" and g.task_name in handler_tasks:
            status = "VERIFIED"
        elif method == "library":
            status = "handler missing"
        elif method == "formula":
            status = "circular"
        else:
            status = method
        lines.append(f"| Verification | {status} |")
        if entry.library:
            lines.append(f"| Library | `{entry.library}` |")
        if entry.function:
            lines.append(f"| Function | `{entry.function}` |")
        if entry.pypi and entry.pypi != "(stdlib)":
            lines.append(f"| PyPI | `{entry.pypi}` |")
    else:
        lines.append(f"| Verification | UNMAPPED |")

    if g.task_name in example_tasks:
        lines.append(f"| Double-blind | VERIFIED (textbook example) |")

    lines.append("")

    # Atom
    if atom:
        lines.append("**Knowledge Atom**\n")
        if atom.content:
            content = atom.content.replace("\n", " ").strip()
            if len(content) > 200:
                content = content[:200] + "..."
            lines.append(f"> {content}\n")
        if atom.source_url:
            lines.append(f"- Source: {atom.source_url}")
        if atom.source:
            source = atom.source.replace("\n", " ").strip()
            if len(source) > 100:
                source = source[:100] + "..."
            lines.append(f"- Citation: {source}")
        if atom.example:
            example = atom.example.replace("\n", " ").strip()
            if len(example) > 200:
                example = example[:200] + "..."
            lines.append(f"- Example: {example}")
        lines.append("")
    else:
        lines.append("**Knowledge Atom**: *missing*\n")

    return "\n".join(lines)


def main():
    """Generate the index and write to file."""
    parser = argparse.ArgumentParser(
        description="Generate Markdown index of all generators",
    )
    parser.add_argument("--output", type=str, default="GENERATOR_INDEX.md",
                        help="Output file path")
    args = parser.parse_args()

    index = build_index()

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(index)

    print(f"Index written to {args.output}")
    print(f"  {len(index):,} characters")
    print(f"  {index.count(chr(10)):,} lines")


if __name__ == "__main__":
    main()
